In [46]:
import pandas as pd

In [41]:
# 데이터 수정
# 권장사항
# df.replace({'학교':{'구로고':'신림고','디지털고':'사거리고'}},inplace=True)
# df['학교'] = df['학교'].replace({'구로고':'신림고','디지털고':'사거리고'})
# df['학교'] = df['학교'].str.replace('구로고','신림고')

#### 데이터수정

In [ ]:
# df['학교'] = df['학교'] + '등학교'
# df['학교'] = df['학교'].str.replace('고','고등학교')
# df['학교'] = df['학교'].str.replace('구로고','포켓몬고')
# df['SW특기'] = df['SW특기'].str.lower()
# df['SW특기'] = df['SW특기'].str.upper()
# df['SW특기'] = df['SW특기'].str.capitalize()

In [91]:
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

#### 데이터추가
* 없는 컬럼값을 입력하면 추가가 됨.

In [92]:
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']

In [93]:
df['결과'] = '불합격'

In [94]:
# 185 이상 출력하시오.
# df[df['키']>=185]
# 350점 이상

# 컬럼 전체를 수정할때 df['컬럼']
# df[df['합계']>=350]['결과'] = '합격'  
# df['국어'] = df['국어']+10
# 컬럼의 부분적인 값을 넣을때는 loc,iloc를 사용
df.loc[df['합계']>=350,'결과'] = '합격'

In [108]:
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['결과'] = '불합격'
df.loc[df['합계']>=350,'결과'] = '합격'

In [110]:
# 컬럼 데이터 삭제 : drop(columns 삭제)
# df.drop(columns=['합계'],inplace=True)
# df.drop(columns=['합계','결과'],inplace=True)

# index 데이터 삭제 : drop(index 삭제)
# df.drop(index='4번',inplace=True)

# df.columns # 전체컬럼 출력
# df.index # 전체index 출력
# 국어점수가 80점 이만 학생 삭제
filt = df['국어']<80
# df[filt].index
# df.drop(index=df[filt].index,inplace=True)
df[~filt]

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계  결과
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  합격
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440  합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  합격

In [101]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455   합격
2번    강태원   구로고  184   40   35   50  55  25        Java  205  불합격
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380   합격
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440   합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465   합격