In [29]:
import pandas as pd

data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

df = pd.DataFrame(data)

In [ ]:
df.info()

In [ ]:
df['관객 수']=df['관객 수'].sort_values(ascending=False)

# 함수사용해서 천단위 쉼표 표시
def so(pep) :
    # return '{:,d}'.format(pep) # 숫자를 문자형으로 변형
    return f"{pep:,}"

df['관객 수'] = df['관객 수'].apply(so)


# map 사용
# df['관객 수'] = df['관객 수'].map('{:,}'.format)
# lambda 사용
df['관객 수'] = df['관객 수'].apply(lambda x: f'{x:,}')

df['관객 수']=df['관객 수'] + '만명'

In [22]:
df['관객 수']

0    1,761만명
1    1,626만명
2    1,441만명
3    1,426만명
4    1,301만명
5    1,298만명
6    1,281만명
7    1,270만명
Name: 관객 수, dtype: str

In [ ]:
def cal(x) :
    return x+2
# (lambda x:x+2) #1줄 함수

In [ ]:
# map 사용
# df['관객 수'] = df['관객 수'].map('{:,}'.format)
# lambda 사용
df['관객 수'] = df['관객 수'].apply(lambda x: f'{x:,}')
df

          영화  개봉 연도   관객 수    평점
0         명량   2014  1,761  8.88
1       극한직업   2019  1,626  9.20
2  신과함께-죄와 벌   2017  1,441  8.73
3       국제시장   2014  1,426  9.16
4         괴물   2006  1,301  8.62
5        도둑들   2012  1,298  7.64
6    7번방의 선물   2013  1,281  8.83
7         암살   2015  1,270  9.10

In [46]:
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

df = pd.DataFrame(data)

In [ ]:
#  개봉연도 내림차순, 오름차순 으로 출력하시오.

#  평점이 9점이상만 출력하시오.

#  평점 컬럼 내용에 8.88점 글자를 넣어서 출력하시오.

# 평점중에 평점 평균이상인 row만 출력하시오.
#2015년 이후에 개봉한 영화를 출력하시오

In [ ]:
#  개봉연도 내림차순, 오름차순 으로 출력하시오.
# df['개봉 연도'].sort_values()
# df['개봉 연도'].sort_values(ascending=False)

#  평점이 9점이상만 출력하시오.
# df[df['평점']>=9]
# filt = df['평점']>=9
# df[filt]

#  평점 컬럼 내용에 8.88점 글자를 넣어서 출력하시오.
# df['평점'] = df['평점'].astype(str)
# df['평점']=df['평점']+'점'

# 평점중에 평점 평균이상인 row만 출력하시오.
# avg = df['평점'].mean()
# df[df['평점']>avg]

#2015년 이후에 개봉한 영화를 출력하시오
# df[df['개봉 연도']>=2015]

        영화  개봉 연도  관객 수    평점
0       명량   2014  1761  8.88
1     극한직업   2019  1626  9.20
3     국제시장   2014  1426  9.16
6  7번방의 선물   2013  1281  8.83
7       암살   2015  1270  9.10