In [84]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [4]:
df.shape

(8, 9)

In [85]:
df['요일'] = 0
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   0
2번    강태원   구로고  184   40   35   50  55  25        Java   0
3번    강호림   구로고  168   80   75   70  80  75  Javascript   0
4번    김수찬   구로고  187   40   60   70  75  80         NaN   0
5번    김재욱   구로고  188   15   20   10  35  10         NaN   0
6번    박동현  디지털고  202   80  100   95  85  80           C   0
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   0
8번    승근열  디지털고  190  100   85   90  95  95          C#   0

In [86]:
import random
for i in range(8) :
    df.iloc[i,9] = random.randint(0,6)

In [ ]:
df['']

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
 9   요일      8 non-null      int64
dtypes: int64(7), str(3)
memory usage: 704.0+ bytes

In [87]:
# 0일 1월 2화 3수 4목 5금 6토

def day(today) :
    if today == 0: return '일요일'
    elif today == 1: return '월요일'
    elif today == 2: return '화요일'
    elif today == 3: return'수요일'
    elif today == 4: return '목요일'
    elif today == 5: return'금요일'
    elif today == 6: return '토요일'

df['요일'] = df['요일'].apply(day)

In [88]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  일요일
2번    강태원   구로고  184   40   35   50  55  25        Java  화요일
3번    강호림   구로고  168   80   75   70  80  75  Javascript  토요일
4번    김수찬   구로고  187   40   60   70  75  80         NaN  수요일
5번    김재욱   구로고  188   15   20   10  35  10         NaN  목요일
6번    박동현  디지털고  202   80  100   95  85  80           C  토요일
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  일요일
8번    승근열  디지털고  190  100   85   90  95  95          C#  화요일

In [57]:
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}

df = pd.DataFrame(data)
df.set_index('번호',inplace=True)

In [42]:
df

     이름       달러   우대
번호
1번  홍길동  $19,700   90
2번  유관순  $18,400   40
3번  이순신  $16,800   80
4번  강감찬  $18,700   40
5번   김구  $18,800   15
6번  김유신  $20,200   80
7번  홍길자  $18,800   55
8번  홍길순  $19,000  100

In [58]:
df['금액'] = 0


#우대 50이상인 사람에게 달려+달러X우대X0.01
#우대 50미만 달러

#달러 -> int 변경($,쉼표 제거)
df['달러'] = df['달러'].str.replace('$','')
df['달러'] = df['달러'].str.replace(',','').astype(int)
df['달러']

def dal(df2):
    if df2['우대'] >= 50:
        df2['금액'] = df2['달러']+(df2['달러']*df2['우대']*0.01)
        return df2['금액']
    else :
        return df2['달러']

df['금액'] = df.apply(dal,axis=1)

In [75]:
df = pd.read_csv('file/jumin08_2.csv')
df2 = df[['행정구역','2026년08월_총인구수']]
df3 = df2[1:6]
df3['2026년08월_총인구수'] = df3['2026년08월_총인구수'].str.replace(',','').astype(int)
df3['2026년08월_총인구수'].sum()

np.int64(21079357)