In [1]:
import pandas as pd
df =pd.read_excel('file/score.xlsx',index_col='지원번호')

In [2]:
#합계,평균,결과 컬럼을 추가
#결과는 평균점수가 70점 이상은 합격 , 불합격으로 출력하시오.
df['합계'] = 0
df['평균'] = 0
df['결과'] = '불합격'
df['합계'] = df['국어']+df['영어']+df['수학']
df['평균'] = df['합계']/3
df.loc[df['평균']>=70,'결과'] = '합격'

In [ ]:
#컬럼순서변경

# df2 = df[['이름','평균','결과']]
# df2
df = df[['이름','평균','결과','학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']]

KeyError: "['학년'] not in index"

['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계', '평균', '결과']

In [ ]:
#[cols 리스트 순서를 변경]
#1.리스트 타입으로 변경후 순서를 변경
cols = list(df.columns)

cols[-2:] #평균 , 결과 컬럼
type(cols[0]) # str -> list 타입으로 변경하려면 [] 로 묶어야함
cols[1:-2] # 타입 list 이름~ 합계 
# cols[0]+cols[-2:]+cols[1:-2] # str + list + list => error 발생
[cols[0]]+cols[-2:]+cols[1:-2] # list + list + list
cols = [cols[0]]+cols[-2:]+cols[1:-2]
#3. 변경된 리스트 적용
df=df[cols]
df

            이름    SW특기   합계         평균   결과    학교  학년    키  국어  영어  수학
번호
1      Eadmund       c  208  69.333333  불합격   신림고   2  171  56  92  60
2       Kirbee       C  108  36.000000  불합격   구로고   1  199  53  10  45
3    Appolonia       C  210  70.000000   합격   구로고   3  193  77  52  81
4        Avery       C  137  45.666667  불합격   구로고   2  187  59  35  43
5       Dallis       C  230  76.666667   합격  디지털고   1  209  97  57  76
..         ...     ...  ...        ...  ...   ...  ..  ...  ..  ..  ..
96        Luke  Python  213  71.000000   합격   신림고   3  187  91  63  59
97        Nada  PYTHON  204  68.000000  불합격   구로고   3  170  60  89  55
98       Fiona       C  276  92.000000   합격   신림고   1  200  97  95  84
99        Leif  PYTHON  214  71.333333   합격   구로고   2  192  96  84  34
100   Jonathan    JAVA  227  75.666667   합격  디지털고   2  195  84  63  80

[100 rows x 11 columns]

In [ ]:
df.value_counts('결과') #그룹으로 개수확인

결과
불합격    72
합격     28
Name: count, dtype: int64

In [ ]:
a_list = [1,2,3]
b_list = [4,5,6]
c_list = a_list+b_list # list 타입일때만 더하기 + 가능
c_list

[1, 2, 3, 4, 5, 6]

In [19]:
df[df.columns[0:3]]

            이름    학교  학년
번호
1      Eadmund   신림고   2
2       Kirbee   구로고   1
3    Appolonia   구로고   3
4        Avery   구로고   2
5       Dallis  디지털고   1
..         ...   ...  ..
96        Luke   신림고   3
97        Nada   구로고   3
98       Fiona   신림고   1
99        Leif   구로고   2
100   Jonathan  디지털고   2

[100 rows x 3 columns]

In [ ]:
#컬럼수정 - replace , 존재하는 컬럼에 값을 입력하면 수정됨
#컬럼추가 - 없는 컬럼에 값을 입력하면 추가됨
#컬럼삭제 - drop : 여러개 삭제 가능 , inplace=True 적용

In [93]:
import pandas as pd
df =pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# row : index수정,추가,삭제
#index 삭제 - 조건사용해서 삭제
#수학점수가 80점미만 학생 삭제

# filt = df['수학'] > 80
# df2 = df[filt]
# df2

# df = df.drop(columns=['평균','결과'],inplace=True)
# df.drop(index=['1번','2번'],inplace=True)
# filt = df['수학'] < 80
# df2 = df[filt].index
# # df.drop(index=df2,inplace=True)

In [80]:
df

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [106]:
import pandas as pd
df =pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
df.columns
# 국어 ,영어,수학,과학,사회 점수 합계컴럼을 추가하고
# 합계 점수가 350이상만 출력하시오

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [ ]:
# 국어,영어,수학,과학,사회 합계 컬럼을 추가하고
# 합계점수가 350점이상만 출력하시오
# 350점 미만 삭제후 출력

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
total = df['합계']>350
df2 = df[~total].index
df.drop(index=df2,inplace=True)

In [104]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
6번    박동현  디지털고  202   80  100   95  85  80           C  440
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [120]:
import pandas as pd
df =pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# 1.index 추가 : loc[] 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동','구로고', 190, 90, 80, 70, 60, 50, 'Python']
# 2. SW특기 부분 값 추가
# df.loc['4번','SW특기'] = 'C' # index 컬럼 지정해서 값 입력
# 3. 부분수정 : 학교,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']] = ['디지털고','python']
# df.loc['5번',['학교','사회','SW특기']] = ['디지털고',50,'Java']

In [116]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬  디지털고  187   40   60   70  75  80      python
5번    김재욱  디지털고  188   15   20   10  35  50        Java
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#
9번    홍길동   구로고  190   90   80   70  60  50      Python

In [123]:
#컬럼 이름 변경 :전체수정
#df.columns = [변경할 이름을 입력]
# df2 = df[['이름','국어','영어']]
# df2.columns = ['name','kor','eng']
# df2

#부분 컬럼이름 변경

# df.rename(columns={'이름':'name','국어':'kor','영어':'eng'},inplace=True)
# df

# df.columns[1] = 'school' 이건안됨
df.rename(columns={df.columns[1]:'school'},inplace=True)
df

     name school    키  kor  eng   수학  과학  사회        SW특기
지원번호
1번    강나래    구로고  197   90   85  100  95  85      Python
2번    강태원    구로고  184   40   35   50  55  25        Java
3번    강호림    구로고  168   80   75   70  80  75  Javascript
4번    김수찬    구로고  187   40   60   70  75  80         NaN
5번    김재욱    구로고  188   15   20   10  35  10         NaN
6번    박동현   디지털고  202   80  100   95  85  80           C
7번    박혜정   디지털고  188   55   65   45  40  35      PYTHON
8번    승근열   디지털고  190  100   85   90  95  95          C#