In [26]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [12]:
#컬럼전체 이름변경
# df['학교'] = df['학교'] + '등학교'
# df.replace({'고':'고등학교'},inplace=True) #안됨
# df['학교'] = df['학교'].str.replace({'고':'고등학교'})

In [ ]:
# 키 + cm

# df['키'] = df['키']+'cm'  #df['키'] : int , 'cm' : str
# 타입이 다른경우 , 타입변경후 적용
# df['키']=df['키'].astype(str) + 'cm' # str으로 타입변환

In [24]:
df['SW특기']

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [21]:
# 함수적용 : apply() - 컬럼 전체에 적용
def add_cm(h) :
    return str(h) + '센치미터'

df['키'] = df['키'].apply(add_cm)
df

       이름    학교        키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197센치미터   90   85  100  95  85      Python
2번    강태원   구로고  184센치미터   40   35   50  55  25        Java
3번    강호림   구로고  168센치미터   80   75   70  80  75  Javascript
4번    김수찬   구로고  187센치미터   40   60   70  75  80         NaN
5번    김재욱   구로고  188센치미터   15   20   10  35  10         NaN
6번    박동현  디지털고  202센치미터   80  100   95  85  80           C
7번    박혜정  디지털고  188센치미터   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190센치미터  100   85   90  95  95          C#

In [29]:
# 함수적용
def capChange(lang) :
    if pd.notnull(lang) : 
        return lang.lower()
    else:
        return '특기없음'


df['SW특기'] = df['SW특기'].apply(capChange)
df['SW특기']

# df['SW특기'].str.lower()

지원번호
1번        python
2번          java
3번    javascript
4번          특기없음
5번          특기없음
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

In [34]:
# 1 . 합계 과목총점을 계산해서 컬럼을 추가하시오.
# 2. 평균 컬럼을 추가하시오
# 3. 등급 컬럼을 추가해서 90점이상 A, 80점 이상 B, 70점이상 c , 60점이상 D , 나머지 F

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['평균'] = df['합계'] / 5

def rank(avg) :
    if avg >=90 :
        return 'A'
    elif avg>=80 :
        return 'B'
    elif avg>=70 :
        return 'C'
    elif avg>=60 :
        return 'D'
    else :
        return 'F'

df['등급'] = df['평균'].apply(rank)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균 등급
지원번호
1번    강나래   구로고  197   90   85  100  95  85      python  455  91.0  A
2번    강태원   구로고  184   40   35   50  55  25        java  205  41.0  F
3번    강호림   구로고  168   80   75   70  80  75  javascript  380  76.0  C
4번    김수찬   구로고  187   40   60   70  75  80        특기없음  325  65.0  D
5번    김재욱   구로고  188   15   20   10  35  10        특기없음   90  18.0  F
6번    박동현  디지털고  202   80  100   95  85  80           c  440  88.0  B
7번    박혜정  디지털고  188   55   65   45  40  35      python  240  48.0  F
8번    승근열  디지털고  190  100   85   90  95  95          c#  465  93.0  A

In [ ]:
# 등수 : ascending= False 역순정렬 , method = 'min'

df['등수'] = df['합계'].rank(ascending=False).astype(int)

In [50]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
df['합계'] = df['국어']+df['영어']+df['수학']
df['평균'] = df['합계'] / 3

In [43]:
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000
4        Avery   구로고   2  187  59  35  43       C  137  45.666667
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667

[100 rows x 10 columns]

In [ ]:
# 등수 : ascending= False 역순정렬 , method = 'min'
# method = 
df['등수'] = df['합계'].rank(ascending=False,method='dense').astype(int)

In [58]:
df.sort_values('합계',ascending=False).head(30)
# df.drop(columns={'평균'},inplace=True)

            이름    학교  학년    키  국어  영어  수학        SW특기   합계  등수
번호
77       Lorna   신림고   1  208  99  98  86      Python  283   1
98       Fiona   신림고   1  200  97  95  84           C  276   2
39         Ban   구로고   1  185  82  94  80      Python  256   3
34      Nollie  디지털고   1  197  84  89  78           C  251   4
62       Sheba  디지털고   1  184  88  90  67           c  245   5
81      Yancey   신림고   3  185  87  92  66      python  245   5
43        Dale   신림고   2  192  91  96  55      PYTHON  242   6
17       Alric   구로고   1  193  68  96  76        JAVA  240   7
52        Buck   신림고   2  187  93  71  75           c  239   8
73       Moise  디지털고   3  185  90  83  65        JAVA  238   9
29     Timoteo   신림고   2  209  77  94  67      Python  238   9
84         Ola  디지털고   3  170  84  77  77  Javascript  238   9
5       Dallis  디지털고   1  209  97  57  76           C  230  10
93       Kiele   구로고   3  193  68  99  62              229  11
100   Jonathan  디지털고   2  195  84  63  80        JAVA  227  12
58     Diahann   구로고   3  184  90  57  78           c  225  13
54         Ula   신림고   3  168  80  59  85        java  224  14
22        Abbe   구로고   1  188  72  65  86           c  223  15
13      Ardene  디지털고   2  161  91  97  33        JAVA  221  16
51   Madeleine  디지털고   1  177  86  55  78              219  17
47      Perkin  디지털고   2  169  82  73  62      python  217  18
65        Kiri   신림고   3  178  64  83  68        JAVA  215  19
32      Hamnet   신림고   3  171  95  55  65  Javascript  215  19
99        Leif   구로고   2  192  96  84  34      PYTHON  214  20
67    Filberto  디지털고   1  196  60  76  78           c  214  20
96        Luke   신림고   3  187  91  63  59      Python  213  21
27      Gordan  디지털고   1  183  90  31  90      PYTHON  211  22
3    Appolonia   구로고   3  193  77  52  81           C  210  23
44    Lisabeth   구로고   3  186  78  79  52           C  209  24
33    Robinson  디지털고   2  181  55  83  70      PYTHON  208  25

In [ ]:
df