In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [4]:
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']

In [5]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
2번    강태원   구로고  184   40   35   50  55  25        Java  205
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  440
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [6]:
df['결과'] = '불합격'
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  불합격
2번    강태원   구로고  184   40   35   50  55  25        Java  205  불합격
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  불합격
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  불합격
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440  불합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  불합격

In [15]:
# df[df['합계']>=350]['결과'] = '합격'
df.loc[df['합계']>=350,'결과'] = '합격'
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455   합격
2번    강태원   구로고  184   40   35   50  55  25        Java  205  불합격
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380   합격
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  불합격
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   80  100   95  85  80           C  440   합격
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  100   85   90  95  95          C#  465   합격

In [16]:
df = pd.read_excel('file/score.xlsx', index_col='지원번호')
df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df['결과'] = '불합격'
df.loc[df['합계']>=350,'결과'] = '합격'

In [26]:
df.drop(index='4번')
df.drop(columns=['합계','결과'])

filt = df['국어']<=80
df[filt].index
df.drop(index=df[filt].index)
df[~filt].index

Index(['1번', '8번'], dtype='str', name='지원번호')