In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [2]:
df['키']>185

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [16]:
df[df['이름'].str.startswith('강')]
df.loc[df['이름'].str.startswith('강')]

df[df['이름'].str.contains('열')]
df['SW특기']
df['SW특기'].str.lower()
df['SW특기'].str.upper()
df['SW특기'].str.capitalize()
langs = ['python','java']
df[df['SW특기'].str.lower().isin(langs)]

df[df['SW특기'].str.lower().str.contains('java',na=True)]
df[df['SW특기'].str.lower().str.contains('java',na=False)]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    강태원  구로고  184  40  35  50  55  25        Java
3번    강호림  구로고  168  80  75  70  80  75  Javascript

In [28]:
import pandas as pd
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
df.columns
df['총 인구수'] = df['총 인구수'].str.replace(',','').astype(int)
df.sort_values('총 인구수',ascending=False,inplace=True)
df['총 인구수']

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0     51159889
9     13715016
1      9323492
2      3251625
16     3214016
4      3041215
15     2516753
3      2357040
12     2136299
14     1782183
13     1729337
11     1591815
10     1510181
6      1440682
5      1398538
7      1093317
17      666226
8       392154
Name: 총 인구수, dtype: int64

In [31]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [39]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
df[df['이름'].str.lower().str.contains('s')]
# df['학교'] = df['학교'].str.replace('고','고등학교')
df['학교'] = df['학교'] + '등학'
df

            이름      학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고등학   2  171  56  92  60       c
2       Kirbee   구로고등학   1  199  53  10  45       C
3    Appolonia   구로고등학   3  193  77  52  81       C
4        Avery   구로고등학   2  187  59  35  43       C
5       Dallis  디지털고등학   1  209  97  57  76       C
..         ...     ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고등학   3  187  91  63  59  Python
97        Nada   구로고등학   3  170  60  89  55  PYTHON
98       Fiona   신림고등학   1  200  97  95  84       C
99        Leif   구로고등학   2  192  96  84  34  PYTHON
100   Jonathan  디지털고등학   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [44]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# # SW특기 java,c
abc = ['java','c']
df[df['SW특기'].str.lower().isin(abc)]['SW특기']
# java가 포함되어 있는 글자를 모두 출력하시오.
df[df['SW특기'].str.lower().str.contains('java',na=True)]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA