## pandas - dataFrame 2차원 데이터

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [6]:
data = {
    '이름':['강나래','강태원','강호림','김수찬','김재욱','박동현','박혜정','승근열'],
    '학교':['신림고','신림고','신림고','신림고','신림고','디지털고','디지털고','디지털고'],
    '키':[197,184,168,187,188,202,188,190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
data

{'이름': ['강나래', '강태원', '강호림', '김수찬', '김재욱', '박동현', '박혜정', '승근열'],
 '학교': ['신림고', '신림고', '신림고', '신림고', '신림고', '디지털고', '디지털고', '디지털고'],
 '키': [197, 184, 168, 187, 188, 202, 188, 190],
 '국어': [90, 40, 80, 40, 15, 80, 55, 100],
 '영어': [85, 35, 75, 60, 20, 100, 65, 85],
 '수학': [100, 50, 70, 70, 10, 95, 45, 90],
 '과학': [95, 55, 80, 75, 35, 85, 40, 95],
 '사회': [85, 25, 75, 80, 10, 80, 35, 95],
 'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']}

In [ ]:
data['키'] #파이썬 딕셔너리 형태

[197, 184, 168, 187, 188, 202, 188, 190]

In [ ]:
#2차원 데이터
df=pd.DataFrame(data) #pandas DataFrame 변경
df.index= ['1번','2번','3번','4번','5번','6번','7번','8번'] # index 추가

In [9]:
df.index= ['1번','2번','3번','4번','5번','6번','7번','8번']

In [10]:
df

     이름    학교    키   국어   영어   수학  과학  사회        SW특기
1번  강나래   신림고  197   90   85  100  95  85      Python
2번  강태원   신림고  184   40   35   50  55  25        Java
3번  강호림   신림고  168   80   75   70  80  75  Javascript
4번  김수찬   신림고  187   40   60   70  75  80
5번  김재욱   신림고  188   15   20   10  35  10
6번  박동현  디지털고  202   80  100   95  85  80           C
7번  박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번  승근열  디지털고  190  100   85   90  95  95          C#

In [26]:
df=pd.DataFrame(data,index=['1번','2번','3번','4번','5번','6번','7번','8번'])
df.index.name='지원번호'
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80
5번    김재욱   신림고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
df['이름'] # Key -이름,학교,키,국어,영어,수학,과학,사회,sw특기

1번    강나래
2번    강태원
3번    강호림
4번    김수찬
5번    김재욱
6번    박동현
7번    박혜정
8번    승근열
Name: 이름, dtype: str

In [13]:
df

     이름    학교    키   국어   영어   수학  과학  사회        SW특기
1번  강나래   신림고  197   90   85  100  95  85      Python
2번  강태원   신림고  184   40   35   50  55  25        Java
3번  강호림   신림고  168   80   75   70  80  75  Javascript
4번  김수찬   신림고  187   40   60   70  75  80
5번  김재욱   신림고  188   15   20   10  35  10
6번  박동현  디지털고  202   80  100   95  85  80           C
7번  박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번  승근열  디지털고  190  100   85   90  95  95          C#

In [18]:
# df.index.name='번호'
df.index.name='지원번호'

In [ ]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80
5번    김재욱   신림고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [28]:
#index삭제를 반영하려면 inplace 적용시켜야 함.
#drop=True : index가 삭제됨
df.reset_index(drop=True,inplace=True) 
# df.reset_index()

In [29]:
df

    이름    학교    키   국어   영어   수학  과학  사회        SW특기
0  강나래   신림고  197   90   85  100  95  85      Python
1  강태원   신림고  184   40   35   50  55  25        Java
2  강호림   신림고  168   80   75   70  80  75  Javascript
3  김수찬   신림고  187   40   60   70  75  80
4  김재욱   신림고  188   15   20   10  35  10
5  박동현  디지털고  202   80  100   95  85  80           C
6  박혜정  디지털고  188   55   65   45  40  35      PYTHON
7  승근열  디지털고  190  100   85   90  95  95          C#