In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('file/합계출산율_2026.xlsx',skiprows=28,nrows=2)
df.set_index('Unnamed: 0',inplace=True)
df.index.name='제목'
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
제목,,,,,,,,,,
출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [5]:
df.index.values # index 안에 유니코드까지 출력이 가능
df.index.values[0]
df.index.values[1]

'합계\xa0출산율'

In [35]:
# index안에 유니코드부분 이름변경
df.rename(index={'출생아\xa0수':'출생아 수'},inplace=True)
df.rename(index={'합계\xa0출산율':'합계 출산율'},inplace=True)
# df.loc['출생아\xa0수']
# df.loc['출생아 수']

In [37]:
# 컬럼 축을 변경
df = df.T   #row,column 축을 변경

In [38]:
df

제목    출생아 수  합계 출산율
2016  406.2   1.172
2017  357.8   1.052
2018  326.8   0.977
2019  302.7   0.918
2020  272.3   0.837
2021  260.6   0.808
2022  249.2   0.778
2023  230.0   0.721
2024  238.3   0.748
2025  254.3   0.800

In [39]:
df['출생아 수']

2016    406.2
2017    357.8
2018    326.8
2019    302.7
2020    272.3
2021    260.6
2022    249.2
2023    230.0
2024    238.3
2025    254.3
Name: 출생아 수, dtype: float64