In [44]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# df['키'].max()
# df['키'].nlargest(3) #최대값 3개
df['키'].nsmallest(3) #최소값 3개

df['학교'].nunique() #중복제거후 리스트
df['학교'].unique() #중복제거후 개수

2

In [4]:
#컬럼의 기본정보 : 타입,크기,이름 , null값 확인
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 640.0+ bytes

In [5]:
# 기본통계 확인 - 숫자타입인 경우, 기본적인 통계
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [6]:
#행렬 크기 확인 8행9열 
df.shape

(8, 9)

In [ ]:

df.head() #상단에 5개만 확인
df.tail() #하단에 5개만 확인
df.head(3) #상단3개만 확인
df.tail(2)
df.values #배열구조로 확인
df.index #index 확인
df.columns # 컬럼확인

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [18]:
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [ ]:
# 1차원데이터 (Series) :  max,min,count,mean,std
df['키'].max() #최대값
df['키'].min() #최솟값
df['키'].count()
df['키'].std()
df['키'].mean()

이름         승근열
학교         신림고
키          202
국어         100
영어         100
수학         100
과학          95
사회          95
SW특기    Python
dtype: object

In [34]:
df = pd.read_excel('file/상장법인목록2.xlsx')

df.info()
df.describe()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     2495 non-null   str
 1   종목코드    2495 non-null   int64
 2   업종      2495 non-null   str
 3   주요제품    2477 non-null   str
 4   상장일     2495 non-null   datetime64[us]
 5   결산월     2495 non-null   str
 6   대표자명    2495 non-null   str
 7   홈페이지    2343 non-null   str
 8   지역      2495 non-null   str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 175.6 KB

(2495, 9)

In [47]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()

# df.describe()
# df.info()
# df.shape
# df.head(10)
# df.set_index('country',inplace=True)
# df.sort_index(ascending=False)

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str