In [ ]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [11]:
# 조건 : 필터 적용해서 조건적용
df['키']>=185  # True,False형태로 출력
df[df['키']>=185]

# 변수로 입력받아 적용
filt = df['키']>=185  
df[filt]
df[~filt]  # ~ not적용

df2 = df[filt]
df3 = df2[['이름','키','국어']]
df3

       이름    키   국어
지원번호
1번    강나래  197   90
4번    김수찬  187   40
5번    김재욱  188   15
6번    박동현  202   80
7번    박혜정  188   55
8번    승근열  190  100

In [ ]:
df3 = df2[df2['국어']>=80]
df[(df['키']>=185) & (df['국어']>=90) ] # & -> and(X)

       이름    학교    키   국어  영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90  85  100  95  85  Python
8번    승근열  디지털고  190  100  85   90  95  95      C#