In [3]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [52]:
df['키'].max()
df['키'].nlargest(3)  # 최대값 3개
df['키'].nsmallest(3) # 최소값 3개

df['학교'].nunique() # 중복제거후 개수
df['학교'].unique() # 중복제거후 리스트

<StringArray>
['신림고', '디지털고']
Length: 2, dtype: str

In [ ]:
# 컬럼의 기본정보 : 타입,null값 확인,이름,개수
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 940.0+ bytes

In [ ]:
# 기본통계 확인 - 숫자타입인 경우, 기본적인 통계
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [5]:
# 크기 확인 (8행9열) rows-8개, cols-9개
df.shape

(8, 9)

In [ ]:
df.head() # 상단에 5개만 확인
df.tail() # 하단에 5개만 확인
df.head(3) # 상단3개만 확인
df.tail(2)
df.values  #배열구조로 확인
df.index   # index확인
df.columns # 컬럼확인

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [22]:
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [24]:
df['키'].max() # 최대값
df['키'].min()
df['키'].count()
df['키'].std()

np.float64(9.98570406702931)

In [ ]:
# 1차원데이터(Series) : max,min,count,mean,std
df['키'].max() # 최대값
df['키'].min()
df['키'].count()
df['키'].mean()

np.int64(8)

In [45]:
df = pd.read_excel('file/상장법인목록2.xlsx')
df.info()
df.shape
df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     2495 non-null   str
 1   종목코드    2495 non-null   int64
 2   업종      2495 non-null   str
 3   주요제품    2477 non-null   str
 4   상장일     2495 non-null   datetime64[us]
 5   결산월     2495 non-null   str
 6   대표자명    2495 non-null   str
 7   홈페이지    2343 non-null   str
 8   지역      2495 non-null   str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 175.6 KB

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,스톤브릿지벤처스,330730,기타 금융업,"창업투자, 사모투자",2022-02-25,12월,유승운,http://stonebridgeventures.vc,서울특별시
1,하나금융21호스팩,406760,금융 지원 서비스업,기업인수합병,2022-02-25,12월,이병찬,NaN,서울특별시
2,브이씨,365900,운동 및 경기용구 제조업,골프용 거리측정기,2022-02-24,12월,김준오,http://www.voicecaddie.co.kr,서울특별시
3,퓨런티어,370090,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","전장카메라모듈장비, 모바일카메라모듈장비, PC및 광원",2022-02-23,12월,배상신,http://www.furonteer.com,경기도
4,바이오에프디엔씨,251120,기초 의약물질 및 생물학적 제제 제조업,식물세포 유래 유효물질 및 약리물질,2022-02-21,12월,"모상현, 정대현",http://www.biofdnc.com,인천광역시
5,한국제10호스팩,409570,금융 지원 서비스업,기업인수합병,2022-02-21,12월,김태훈,NaN,서울특별시
6,IBKS제17호스팩,405350,금융 지원 서비스업,금융 지원 서비스,2022-02-18,12월,이경준,NaN,서울특별시
7,인카금융서비스,211050,보험 및 연금관련 서비스업,보험 판매,2022-02-16,12월,최병채,http://www.incar.co.kr,서울특별시
8,나래나노텍,137080,특수 목적용 기계 제조업,"디스플레이 장비 (포토, 코팅, 모듈 장비)",2022-02-08,12월,정좌진,http://www.naraenano.co.kr,경기도
9,아셈스,136410,플라스틱제품 제조업,핫멜트 접착 필름,2022-02-07,12월,장지상,http://assems.com,부산광역시

In [6]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()
# df.describe()
# df.info()
# df.shape
# df.head(10)
# df.set_index('country',inplace=True)
# df.sort_index(ascending=False)

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str