#### save

In [ ]:
# concat : DataFrame 합치기 , usecols : 컬럼선택해서 가져오기
# skiprows : 상단부분 제외후 가져오기

In [42]:
import pandas as pd
data = {
    '이름':['강나래','강태원','강호림','김수찬','김재욱','박동현','박혜정','승근열'],
    '학교':['신림고','신림고','신림고','신림고','신림고','디지털고','디지털고','디지털고'],
    '키':[197,184,168,187,188,202,188,190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}

df = pd.DataFrame(data,index=['1번','2번','3번','4번','5번','6번','7번','8번'])
df.index.name = '지원번호'

In [ ]:
# 파이썬에서 파일저장
# with open('score.csv','w') as f:
#     pass

In [ ]:
# csv파일저장 - csv,txt,xlsx
# database프로그램과 호환가능
df.to_csv('file/score.csv',encoding='utf-8-sig') #utf-8-sig:excel파일에 확인가능

In [15]:
# txt파일저장
# df.to_csv('file/score.txt')         # ,쉼표를 기준으로 분리
# df.to_csv('file/score2.txt',sep='\t') # 탭간격으로 분리
df.to_csv('file/score3.txt',sep='*') # 탭간격으로 분리

In [ ]:
# xlsx 파일저장
df.to_excel('file/score.xlsx')
df.to_excel('file/score_2.xlsx',index=False) # index제외후 저장

In [21]:
# 파일읽기 - read : csv,txt,xlsx
# skiprows : 상단2줄을 제외하고 가져옴
# df = pd.read_csv('file/score.csv')
# df = pd.read_csv('file/score.csv',skiprows=1)
df = pd.read_csv('file/score.csv',skiprows=[1,3,5])
df

  지원번호   이름    학교    키   국어   영어  수학  과학  사회    SW특기
0   2번  강태원   신림고  184   40   35  50  55  25    Java
1   4번  김수찬   신림고  187   40   60  70  75  80     NaN
2   6번  박동현  디지털고  202   80  100  95  85  80       C
3   7번  박혜정  디지털고  188   55   65  45  40  35  PYTHON
4   8번  승근열  디지털고  190  100   85  90  95  95      C#

In [ ]:
# nrows : 설정한 줄만큼 가져옴
df = pd.read_csv('file/score.csv',skiprows=1, nrows=4)
df = pd.read_csv('file/jumin08_2.csv',skiprows=1)

In [39]:
# txt파일 불러오기
df = pd.read_csv('file/score.txt')
# df = pd.read_csv('file/score.txt', sep='\t') #저장할때 구분자로 불러오기
# df = pd.read_csv('file/score.txt', sep='*')
# df['이름']

In [ ]:
# xlsx파일 불러오기 - index지정해서 가져오기 : index_col
# df = pd.read_excel('file/score.xlsx')
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#