In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [8]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [ ]:
# df.columns 컬럼리스트
df.columns
# df[컬럼이름]
df['이름']
# df[[컬럼이름,컬럼이름]] : 2개이상일때 []리스트형태로
df[['이름','수학']]
# df['이름':'과학']  # 슬라이싱 안됨.
df[df.columns[0:4]] # columns를 사용해서 슬라이싱 적용
df.loc[:,'이름':'수학'] # loc를 사용해서 슬라이싱 가능
df[0:3]      # index에 해당되는 3개 출력
df.iloc[0:3] #index에 해당되는 3개 출력

df[df.columns[-1]] # 마지막 컬럼 출력
df[df.columns[[0,3,-1]]]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  구로고  197  90  85  100  95  85      Python
2번    강태원  구로고  184  40  35   50  55  25        Java
3번    강호림  구로고  168  80  75   70  80  75  Javascript

In [8]:
# loc 출력 : 이름으로 출력
# loc [[index이름:],[컬럼이름:]]
# df.loc['1번']
# df.loc[['1번','2번']]
# df.loc['1번':'5번']
# df.loc['1번','이름':'수학'] # 슬라이싱
# df.loc['2번':'5번','이름':'수학'] # 슬라이싱
# df.loc[['1번','3번'],'이름':'수학'] # 슬라이싱

       이름   학교    키  국어  영어   수학
지원번호
1번    강나래  구로고  197  90  85  100
3번    강호림  구로고  168  80  75   70

In [40]:
# iloc 출력 - 리스트번호로 출력
df.iloc[0]
df.iloc[0:4]
df.iloc[[0,1,4]]
df.iloc[0:4,1:5]
df.iloc[[1,5],1:5]

        학교    키  국어   영어
지원번호
2번     구로고  184  40   35
6번    디지털고  202  80  100

In [42]:
df['키']

지원번호
1번    197
2번    184
3번    168
4번    187
5번    188
6번    202
7번    188
8번    190
Name: 키, dtype: int64

In [ ]:
# 조건 : True,False 리턴
# df['키']>185
df[df['키']>185]['키']

지원번호
1번    197
4번    187
5번    188
6번    202
7번    188
8번    190
Name: 키, dtype: int64

In [45]:
df[df['국어']>=80]

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
3번    강호림   구로고  168   80   75   70  80  75  Javascript
6번    박동현  디지털고  202   80  100   95  85  80           C
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [9]:
df[df['키']>190]['학교':'과학']

Empty DataFrame
Columns: [이름, 학교, 키, 국어, 영어, 수학, 과학, 사회, SW특기]
Index: []

In [10]:
# df.loc [ (index)row, column ]
df.loc[df['키']>190,'학교':'수학']

        학교    키  국어   영어   수학
지원번호
1번     구로고  197  90   85  100
6번    디지털고  202  80  100   95

In [56]:
df.loc[(df['키']>185) & (df['학교']=='디지털고')]
df.loc[(df['키']>185) | (df['학교']=='디지털고')]
df.loc[(df['국어']>85) | (df['수학']>90)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#