In [2]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False     # - 부호처리
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # 한글처리 : 윈도우 맑은고딕 저장
matplotlib.rcParams['font.size'] = 15                 # 전체 글자폰트크기 조정
# matplotlib.rcParams['font.family'] = 'AppleGothic'    # 맥컴 애플고딕 저장
import pandas as pd
import numpy as np
import re          # 정규표현식

In [3]:
df = pd.read_csv('file/namu2.csv')
df['content'].head(3)

0    라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
1    경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오.보드게임 '벚꽃 내...
2    군산시시내버스 노선[ 펼치기 · 접기 ]미성동010203070809옥구읍111213...
Name: content, dtype: str

In [3]:
# 글자에 대한 전처리작업 - 한글이외 글자 삭제, 필요없는 글자 삭제
def text_cleaning(text):
    if pd.isna(text):
        return ''
    hangul = re.compile('[^ ㄱ-ㅣ가-힣]+')    # 정규표현식에 해당이 되는지 확인
    return hangul.sub('',text)

In [4]:
df.head()

,Unnamed: 0,title,category,content
0,0,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
1,1,경지,경지나무위키 웹소설 프로젝트무공칭호(무협),경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오.보드게임 '벚꽃 내...
2,2,군산 버스 19,군산시의 시내버스,군산시시내버스 노선[ 펼치기 · 접기 ]미성동010203070809옥구읍111213...
3,3,House 2,2026년 Windows 게임미국 게임액션 어드벤처 게임호러 게임,하우스 2House 2개발Bark Bark Games유통Glowstick Enter...
4,4,장갑기병 보톰즈 회색의 마녀,보톰즈 시리즈일본 애니메이션/목록2026년 애니메이션 영화2026년 4분기 일본 애...,로도스도 전기에 등장하는 '회색의 마녀'에 대한 내용은칼라(포세리아)문서를 참고하십...

In [5]:
# 한글 이외 모든 문자 삭제
df['title'] = df['title'].apply(lambda x : text_cleaning(x))
df['category'] = df['category'].apply(lambda x:text_cleaning(x))
df['content'] =df['content'].apply(lambda x:text_cleaning(x))
df.head(3)

,Unnamed: 0,title,category,content
0,0,조지 웨아,년 출생년 데뷔년 은퇴년 은퇴라이베리아 대통령라이베리아의 남자 축구 선수공격수 모나...,라이베리아 공화국 대통령 펼치기 접기 초대제대제대제대조셉 젠킨스 로버츠스티븐 앨런...
1,1,경지,경지나무위키 웹소설 프로젝트무공칭호무협,경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오보드게임 벚꽃 내리는...
2,2,군산 버스,군산시의 시내버스,군산시시내버스 노선 펼치기 접기 미성동옥구읍대야면회현면성산면임피면서천군시내선심야 ...

In [6]:
df['title']

0                         조지 웨아
1                            경지
2                        군산 버스
3
4               장갑기병 보톰즈 회색의 마녀
5                   카드 앙 시엘카드드로
6                           사용자
7                      제단워크래프트
8                          빅 미키
9                        제임스 로니
10              제보병사단  지뢰 폭발 사건
11                           탱킹
12                           와다
13
14
15             명탐정 코난 시한장치의 마천루
16                     제단워크래프트
17                        영천시정치
18    극장판 이나즈마 일레븐 최강군단 오우거의 습격
19
20                     년 이라크 봉기
21       쇼트트랙 스피드 스케이팅 유럽선수권 대회
22         불꽃 파이터즈역대 전적 시즌경기 목록
23                         흑색왜성
24
25            김환희골 때리는 그녀들클럽 경력
26
27               사용자빠른 이동 및 연습장
28                         난칸마치
29
30                           손무
31                         폴로네즈
32       쇼트트랙 스피드 스케이팅 유럽선수권 대회
33                          정비사
34         불꽃 파이터즈역대 전적 시즌경기 목록
35          분류바트주의 이라크의 전쟁 및 전투
36      김환희골 때리는 그녀들클럽 경력 액셔니스타
37                안양 정관장 레드부스터스
38           잔스파인건담 지 제네레이션 이터널
39                          사용자
40                   부산 저축은행 읏맨
41
42
43                토오사카 린작중 행적본편
44                 김주성야구선수선수 경력
45               리그 오브 레전드증강프리즘
46                        조지 웨아
47                          사용자
48                         아스파르
49                          년사건
Name: title, dtype: str

In [7]:
# 각 컬럼마다 컬럼을 모두 1개의 문자열로 변환
titles = " ".join(df['title'])
categorys = " ".join(df['category'])
contents = " ".join(df['content'])
contents

'라이베리아 공화국 대통령 펼치기  접기 초대제대제대제대조셉 젠킨스 로버츠스티븐 앨런 벤슨대니얼 바시엘 워너제임스 스프릭스 페인제대임시제대제대에드워드 제임스 로이최고임원위원회제임스 스키브링 스미스조셉 젠킨스 로버츠제대제대제대제대제임스 스프릭스 페인앤서니  가디너앨프리드 프랜시스 러셀힐러리   존슨제대제대제대제대조셉 제임스 치즈먼윌리엄  콜먼개럿슨  깁슨아서 바클레이제대제대제대제대대니얼 에드워드 히워드찰스   킹에드윈 바클레이윌리엄 터브먼제대제대임시임시윌리엄 톨버트새뮤얼 케니언 도애이머스 소여데이비드  크포르막포르임시임시제대제대윌턴   산카울로루스 페리찰스 테일러모지스 블라임시제대제대제대주드 브라이언트엘런 존슨 설리프조지 웨아조셉 보아카이라이베리아 부통령조지 웨아의 수상 이력 펼치기  접기 둘러보기 틀 모음개인 수상아프리카 올해의 축구 선수  득점왕 발롱도르  올해의 선수 옹즈도르베스트팀  올해의 팀  올해의 선수수상호나우두위조지 웨아위앨런 시어러    수상호나우두위앨런 시어러위조지 웨아      에릭 칸토나조지 웨아마티아스 자머조지 웨아의 기타 정보 펼치기  접기     펼치기  접기 에바니코스타쿠르타네스타피를로안퀼레티모라안첼로티갈리말디니아비아티세도르프마사로베컴사비체비치알베르티니쿠디치니갈리인자기바레시가투소게치갈리로데티트라파토니알타피니칼라제슈넬링거후이 코스타드사이카푸암브로시니지다말디니데 베키카카도나도니굴리트보반질라르디노보피파투세브첸코인자기리베라산타고스티노그렌노르달파팽조던알타피니스키아피노호나우두시모네반 바스텐헤이틀리콤빈비어호프프라티비르디스윌킨스카카바조호나우지뉴이브라히모비치 세브첸코웨아리베라파팽반 바스텐카카굴리트비곤벳세베니니말데라스카리오니보노미소르마니트레레안노바치로바티말디니사니모란디솔데라자가티바레시레이카르트리베라모레티안토니니노르달푸리첼리킬핀부폰반 헤게키아루지페르베르시로사토살라암브로시니타소티리드홀름토뇬말디니부리니안토넬리베네티부리아니아르카리로시세르지뉴바티스티니실바노벨리노선정 남자축구 레전드 펼치기  접기 펠레디에고 마라도나로타어 마테우스페렌츠 푸스카스바이충 부티아알리 다에이디노 조프로베르토 바조나카타 히데토시차범근자셈 야쿱조지 웨아안토니오 카르바할라바 마제르우고 산체스요한 크루이프마르코 반 바스텐루드 굴리트윈턴 루퍼알프레도 디 스테파노호나우두라이언 긱스루카스 라데베랜던 도노반후안 알베르토 스키아피노스탠리 매튜스데이비드 베컴바비 찰튼올레흐 블로힌탄주 촐라크프란시스코 헨토마제드 압둘라레프 야신루이스 피구에우제비우호세 루이스 칠라베르트은완코 카누미셸 플라티니프란츠 베켄바워게르트 뮐러모하메드 아부트리카마흐무드 엘카팁지네딘 지단가린샤지쿠로저 밀러쑨지하이하오하이둥프랑코 바레시가브리엘 바티스투타데니스 베르캄프즈비그니에프 보니에크호베르투 카를루스페트르 체흐안드리 셰브첸코케니 달글리시에드가 다비즈알레산드로 델 피에로디디에 드록바사무엘 에투엔조 프란체스콜리게오르게 하지티에리 앙리올리버 칸카카케빈 키건마리오 켐페스미로슬라프 클로제로날드 쿠만필립 람미카엘 라우드루프유니스 마흐무드파올로 말디니라파엘 마르케스파벨 네드베드모하메드 누르제이제이 오코차아베디 펠레장마리 파프안드레아 피를로카를레스 푸욜라울 곤살레스프랑크 레이카르트히바우두호마리우호나우지뉴파올로 로시카를하인츠 루메니게페테르 슈마이켈흐리스토 스토이치코프다보르 슈케르프란체스코 토티카를로스 발데라마뤼트 판니스텔로이로빈 반 페르시사비 에르난데스라이베리아 공화국 제대 대통령조지 웨아 본명조지 타울론 마네 오퐁 오스만 웨아     출생년월 일세라이베리아몬로비아국적라이베리아프랑스신체키체중주발오른발직업축구 선수스트라이커은퇴축구 감독은퇴정치인경력선수영 서바이버스 클래리턴 봉레인지 컴퍼니 마이티 바롤인비서블 일레븐아프리카 스포츠 내셔널 토네르 야운데  모나코 파리 생제르맹  밀란첼시  임대맨체스터 시티 올랭피크 드 마르세유알 자지라 클럽감독라이베리아 대표팀 선수 겸 감독정치민주변화회의라이베리아하원의원몽세라도 주제대대통령년월 일년월 일국가대표경기골라이베리아 링크정보 더 보기 펼치기  접기 학력디브라이 대학교경영학  석사종교개신교라이베리아 연합감리교회배우자클레어 웨아자녀조지 웨아 주니어티모시 웨아등 슬하 명 개요 선수 경력 클럽 경력 모나코파리 생제르맹 밀란첼시 맨체스터 시티 올랭피크 드 마르세유알 자지라 클럽 국가대표 플레이 스타일 축구 선수로서의 평가 정치인 경력 기록 대회 기록 개인 수상 웨아에 대한 언사 여담개요편집라이베리아의축구 선수출신정치인선수 시절에는 모나코파리 생제르맹 밀란등 유명 팀들을 두루 거치며아프리카인으로는 유일하게발롱도르와 올해의 선수를 수상한 인물이다년에 치러진 제 대 라이베리아 대통령 선거에서대통령으로 당선되었으며 년 월 일에 취임 했다 년 재선에 도전 하였으나 통일당 후보에게 밀려 낙선 했으며 년 월 일 년 임기를 마쳤다선수 경력편집클럽 경력편집그의 부모님은 라이베리아의 소수 민족크루족으로 낙후 된 지역인 그랜드크루 주에서 수도 몬로비아로 이주해 빈민가인 클라라 타운에 정착하였다 불우한 어린 시절을 보냈으며 가족 관계에도 문제가 있어 웨아는 할머니 손에 자랐다년 세 때 부 리그 소속 지역 축구 클럽인 영 서바이버스 클래리턴과 계약 하며골키퍼로 축구를 시작하였다 하지만 골을 넣는 것에 대한 즐거움을 느끼게 되면서 공격수로 전향 했다년 봉레인지 컴퍼니 유스팀으로 이적 하였다가 년 마이티 배럴에서 프로 선수로 데뷔 하였다 마이티 배럴에서 경기에 출전해 골을 기록 하며 활약 하였고 년 라이베리아 최고의 팀이었던 인빈시블 일레븐으로 이 적하였다 이 클럽에서주장을 맡고 경기에 출전해 골을 기록 하며리그 득점왕에 올랐다이 활약으로 카메룬 스카우트의 눈에 띄어 년 코트디부아르 리그 소속의 아프리카 스포츠 내셔널로 이적 하였다가 카메룬 리그의 토네르 야운데로 이적 하였다 토네르 야운데에서 경기 골을 기록 하며 활약을 이어갔다 모나코편집아프리카에서는 이름을 알리기 시작 했지만사실상 무명인 상태의 조지 웨아를 발탁 하여 국제 무대로 데려와서 성장시킨 인물은아르센 벵거였다 벵거는 아프리카로 직접 가서 웨아의 모습을 수차례 지켜보았고 년 벵거 감독이 이끄는 모나코 로 이적 했다열악한 아프리카 리그에서 쥐꼬리만 한 연봉을 받으며 가족을 부양 했던 웨아는 당시 여러모로 열악한 상태였다 사인을 하러 모나코에 왔을 때 당장 쓸 용돈이 한 푼도 없었기에 벵거 감독이 용돈으로 프랑을 줄 정도였다 게다가 설상가상으로 팔이 골절 된 상태였다구단에서도 의문을 표시 했으나아르센 벵거는 웨아를 전적으로 신임 하며열심히 하면 너는 최고의 선수가 될 수 있다라고 격려 했다그리고 진짜 그렇게 되었다웨아는 모나코에서 잠재력을 폭발시키며 년쿠프 드 프랑스에서 우승하였고 이듬 해에는 팀을 컵위너스컵결승전으로 이끌었다 모나코에서 시즌 동안 경기에 출장해 골을 기록 했다파리 생제르맹편집년파리 생제르맹으로 이적 했다 이적한 뒤 첫 시즌인 시즌에쿠프 드 프랑스에서 우승 시즌에는 리그 앙 우승을 거머쥐었다시즌은 조지 웨아의 선수 커리어 중 가장 영광스러운 시즌이었다쿠프 드 프랑스와쿠프 드 라 리그에서 우승 하여도메스틱 컵 더블을 달성 했고 골을 넣으며 챔피언스 리그 득점왕을 달성 하면서바이에른과바르사를 꺾고 클럽 역사상 처음으로 챔피언스 리그 준결승 까지 진출 하는 데 기여 했다웨아는 파리 생제르맹에서 시즌 동안 경기에 출장해 골을 기록 했다 밀란편집년 여름에 밀란으로 이적 했다 지난 시즌의 활약으로 발롱도르를 수상 받으며 첫 비 유럽인 발롱도르 수상자가 되었다또한 웨아는 밀란 시절  경이적인 신체 능력을 보여주며블랙 다이아몬드라고 불렀다년 월 일 베로나 전에서 를 질주 하여 넣은 골은 그의 클래스를 보여준다 이 골은현재 까지 영상 자료가 존재하는개인이 드리블로 돌파해 넣은 골 중 역대 최장거리 기록으로 알려져 있으며지금 까지도치달의 상징이자축구 역사상 최고의 골 중 하나로 여겨진다 밀란에서의 골 밀란에서 회 리그 우승을 이끌며 시즌 동안 경기에 출장해 골을 기록 했다또한 년 월대한민국 축구 국가대표팀과 친선 경기 목적으로 밀란소속으로 방한한 적이 있다 결과는 으로 한국의 역전승첼시 편집년첼시로 임대되어 경기에 출장해 골을 기록하며 팀의컵우승을 이끌었다맨체스터 시티 편집이후 년 여름맨체스터 시티로 이적하여 경기에 출장하였다올랭피크 드 마르세유편집이후 올랭피크 드 마르세유로 이적해 경기 골을 기록하였다알 자지라 클럽편집년 아랍에미리트의알 자지라 클럽으로 이적해 경기 골을 기록하였고 년 선수 생활을 마감하였다국가대표편집알프레도 디 스테파노조지 베스트라이언 긱스등과 더불어 선수로서의 명성에 대비되는 저조한 국대 커리어를 가진 선수로 자주 거론되는 선수로 허약한 그의 조국 대표팀을 이끌고 고군분투했으나 팀의 한계를 극복하지 못한 채 국가대표 무대에서는 두각을 드러낼 기회조차 없었던 선수로 요약될 수 있다라이베리아 축구 국가대표팀은월드컵은 물론아프리카 네이션스컵조차 예선 탈락이 다반사로 아프리카 내에서도 약체로 분류되는 선수단이었다년 월 일 서아프리카 네이션스컵 나이지리아 전에서 데뷔하였고 그 경기에서 데뷔골도 기록하였다 라이베리아 축구 국가대표팀은 정치권의 부정부패 때문에 충분한 지원을 받지 못해 웨아는 국가대항전 본선이 있을 때마다 사비를 털어야 했다 라이베리아 팀의 주장으로 월드컵 본선 진출을 위해 도전했으나 꿈을 이루진 못하였다 심지어  한일 월드컵 때에는 세의 노장이었던 그는 선수 겸 감독을 맡았지만 같은 조의 나이지리아에 승점 단 점 차로 밀려 아깝게 본선 진출에 실패했다 대신 년 아프리카 네이션스컵에서 본선에 진출했고 말리와의 경기에서 골을 기록하였다년 라이베리아 현지시각 월 일에현직 대통령 신분으로 주장 완장을 차고 나이지리아와의 매치 친선전에 나서며 뒤늦은 국가대표 은퇴 경기를 소화했다 현역 시절 자신의 등번호였던 번을 달고 뛰었는데 라이베리아 축구 국가대표팀의 번을 영구결번하기 위해서 만들어진 경기라고 한다 조지 웨아는 분간 경기를 뛰고 교체되었고 라이베리아는 나이지리아에 아쉽게 대로 패하였다플레이 스타일편집만능 완성형 포워드폭발적인 주력을 낼 수 있으면서도 강인한 힘으로 상대 수비를 이겨낼 수 있는탄력적이면서도 강인한 신체 조건를 가졌다 이 신체적 능력을 십분 활용 하며 상대 수비를 박살내고 골을 집어넣던 선수였다거기에 더해진 좋은퍼스트 터치와 준수한드리블 패스 크로스 능력이 합쳐지고 그 위에 더해진오프 더 볼능력이 웨아를 당대발롱도르 수상자로 만들었다축구 선수로서의 평가편집명실상부 아프리카 역대 최고의 선수 중 한 명으로 평가 받는다로저 밀러디디에 드록바사디오 마네야야 투레피에르에메릭 오바메양등 걸출한 아프리카인 축구 선수들이 있지만 그들을 넘어사무엘 에투모하메드 살라와 함께아프리카 역대 최고의 축구 선수로 평가 된다정치인 경력편집정치인으로 활동 중인 모습내전으로 상처받은 조국 라이베리아를 위해 조지 웨아 기금을 설립하는 등 라이베리아 유니세프 친선 대사로 활동하였다 이후 정치인으로 변신해년 라이베리아 대통령 선거에 일종의 제지대격 포퓰리즘 빅텐트 우익 정당인 민주적 변화를 위한 회의 후보로 출마하였다 차 투표에서는 표로 후보 중 위를 기록했지만 결투표 결과 표를 획득하며 표를 획득한 유엔 개발 프로그램의 아프리카 담당 재정국장으로 철의 여인이라고 불린 중도 자유주의 성향인 통일당  소속의엘런 존슨 설리프 에 표 차이로 패하였다 엘런 존슨설리프  는 번 연임하며 년 임기를 모두 채웠다년 월 일 치러진 대선에 출마했는데 차 투표에서 를 받아 결선 투표에 진출했다 결국 결선 투표에서 대통령으로 당선되었고년월 일에 취임했다그런데 러닝메이트인 부통령 후보로 독재자찰스 테일러의 전 부인을 선택하고 옥중의 찰스 테일러와도 연락하여 논란이 되었으며 심지어 선거에서도 찰스 테일러의 정당이었던 극우국가애국당과 연합을 해서 이겼다이게 보통 일이 아닌 것이 테일러는 그저 평범한 독재자가 아닌 아프리카 독재자들 중에서도 최악이라 평가받는 인물로 라이베리아 내전의 주범이자 아프리카에서도 손꼽히는 대량학살자이며 현재 재판에서 년형을 선고받고 수감 중에 있다심지어 조지 웨아는 상기되어 있듯이 이 내전 당시평화운동가로 활동한 적이 있다취임 후 년이 넘은 년 월 기준으로 달러 대비 라이베리아 달러 화폐 가치가 확 떨어지고 물가가  가까이 상승하여 경제적 불확실성에 시달리고 있다 경제 성장률은 에서 로 추락하고 먹고 살기 어려워진 시민 여 명이인플레이션과 부패에 항의하여 거리시위를 하고 있다 이에 조지 웨아 대통령은 현지시간 월 일에 연설에서 자신을 비난하는 시위자들에게 국가를 위협한다라며 용납하지 않겠다고 밝혔다그 이후 년 대선에서 결선 투표 끝에 낙선했다기록편집대회 기록편집마이티 배럴 라이베리아 프리미어 리그 라이베리아컵 인비서블 일레븐 라이베리아 프리미어 리그  모나코쿠프 드 프랑스 파리 생제르맹 디비지옹  쿠프 드 프랑스  쿠프 드 라 리그  밀란세리에   첼시 컵 개인 수상편집발롱도르  올해의 선수 아프리카 올해의 축구 선수   디비지옹 올해의 외국인 선수  챔피언스 리그득점왕 아프리카 올해의 축구 선수 옹즈도르 옹즈 드 옹즈   올해의 팀     리저브   페어플레이상 엘 파이스 유럽 축구의 왕  올해의 선수 세기의 아프리카 선수  레전드  올타임 아프리카 드림팀     용기상 골든풋  밀란 명예의 전당 발롱도르 드림팀후보   위웨아에 대한 언사편집조지 웨아는 놀라운 선수다 나는 웨아 만큼 피치에서 폭발력을 지닌 선수를 본 적이 없다아르센 벵거조지 웨아는 내 선수 생활에 가장 큰 영향을 주었던 선수이자 나의 우상이다티에리 앙리여담편집조지 웨아 본인과는 아무 상관이 없지만 본인의 이름이 팔려 의문의 패를 당한 황당한 과거가 있다그레이엄 수네스문서 참조집안의 거의 모든 구성원이 사실상 축구선수인데 사촌인 크리스토퍼 웨아와 스티븐 웨아를 시작으로 장남인 조지 웨아 주니어 미국 뉴욕에서 태어난 차남티모시 웨아 친조카패트릭 웨아 그리고 처조카카일 던컨이 축구선수이다영어와프랑스어가 유창하다 기본적으로 라이베리아 공용어가 영어고리그 에서 오래 뛰었기 때문이다조지 웨아 이전에도 축구선수 출신대통령이 있었다 년부터 년까지 재임한카페 필류전브라질대통령이 최초의 축구선수 출신 대통령이고 두 번째도 브라질 대통령을 지낸주앙 굴라르이며 세 번째는튀르키예의에르도안이다 조지 웨아 이후에는조지아에서미헤일 카벨라슈빌리가 내각제 개편 이후의 간선제이긴 하지만 대통령이 되었다물론 발롱도르까지 수상한 월드클래스 레벨의 프로 축구선수가 대통령까지 된 케이스는 아직까지 웨아가 유일하다대통령 퇴임 후 년발롱도르시상식에 시상자로 등장해로드리에게 발롱도르를 수여했다자신의 아들인 티모시 웨아와 함께 와 마르세유에서 모두 선수로 뛴 기록을 가지고 있다피파 시리즈와피파 온라인에   선수로 출시되어 큰 인기를 누렸다 정계에 진출하면서피파 부터는 삭제되었다파리 생제르맹 에서 뛸 때 프랑스 시민권을 취득했다 라이베리아 대선에 출마할 당시 이중국적 때문에 대선 출마가 좌절될 뻔했으나 라이베리아 법원에서 대선 출마에 문제가 없다고 판결을 내려 웨아는 라이베리아 대선에 출마대통령에 취임할 수 있었다선수 시절년에 세의 나이로 자신의 마지막 매치 경기를 치렀다라이베리아 축구 국가대표팀역대 최다 득점자년 졸업본래부터기독교가정에서 태어난 기독교인이었다가이슬람으로 개종한 후 다시 기독교로 개종했다 꽤나 논란이 있는나이지리아라고스의초교파은사주의대형 교회인    티비 조슈아설립에서프린스 존슨과 함께 목격되기도 하였다막내딸은 클레어 웨아에게서 태어나지 않은 이복자녀이며 년생이다이후 아프리카 국적 선수의 포디움 수상은 조지 웨아 자신의 년  올해의 선수 위사무엘 에투의 년  올해의 선수 위모하메드 살라의 년과 년  올해의 선수 위사디오 마네의 년 발롱도르 위가 전부였다디디에 드록바는 년 발롱도르 위에 그쳤다웨아는 밀란에서발롱도르를 수상한 뒤 벵거에게 공을 돌렸다 벵거는 자신이 발탁한 선수 중 가장 대단한 선수로 아직도 웨아를 꼽는다년까지 발롱도르는 유럽인으로 한정 해서 발롱도르를 뽑았으며 이 때문에펠레나마라도나같은 축구의 신들 조차도 발롱도르를 수상 받지 못 했다기록으로만 남아 있는 역대 최장거리 골은펠레의 골이다 무려자기 팀 골대 앞에서 부터 상대 팀 골대 바로 앞 까지 를 혼자서 뚫어버리고 넣은 골로이는 현재 라디오 중계 자료만 남아 있어 제대로 된 세계 기록으로는 인정 받지는 못 한다참고로 번째로 긴 드리블 돌파 후 골의 주인공은 다름 아닌손흥민이다 바로 그 유명한  시즌 번리전의  돌파 후 골웨아랑 고작  차이만 난다 이거 역시 영상이 남아 있다조지 웨아 라이언 긱스 등과는 달리 국대를 하필 그 국대가 가장 약했던 시기만 골라 옮겨다녔기 때문이다 스페인 축구팀과 아르헨티나 축구팀에서 뛴 바 있기 때문에 월드컵 커리어는 매우 부실하지만 소속 국가대표만은 매우 화려하다이는 셰브첸코나 긱스 베일도 극복하지 못한 약체국의 필연이었다 그나마 셰브첸코와 베일은 월드컵에 한번은 나갔다무패로 탈락하였다 경기 말리전 경기 알제리전 모두 점차로 앞서다가 경기종료를 얼마 안 남겨두고 동점골을 내주었고 나이지리아 전은 지면서 아쉽게 탈락하였다년노벨평화상수상이는 스포츠 선수가 정치에 얼마나 큰 영향을 끼칠 수 있는지 보여주는 사례이다 독재자에 대한 반감마저 덮어버릴 정도로 영웅 취급을 받았다는 소리다 물론 조지 웨아도 찰스 테일러 지지층이 아직 살아있으니 이걸 이용한 것이었다물가가 상승하기 직전에 억  라이베리아 달러를 새로 찍어냈다고 한다조지 웨아의  모나코 시절 부터 그의 팬이었다고 한다년생으로 밀란유스 출신이며 년 미국 청소년 대표팀에 출장했으나 대성하지 못한 채 년 커리어를 마감했다성인 대표팀은 자신이 태어난 곳인미국을 선택했다카벨라슈빌리와 웨아는 둘 다 현역 시절맨체스터 시티 에서 뛰어봤다는 공통점이 있다 다만 소속 시기가 달라 만난 적은 없다과거에도  에 합류한호마리우가 정계에 진출하면서 라이센스에서 삭제된 적이 있었다 경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오보드게임 벚꽃 내리는 시대에 결투를의 여신 토코요가 가지는 키워드에 대한 내용은벚꽃 내리는 시대에 결투를카드토코요문서의번 문단을 참고하십시오외모지상주의의 설정에 대한 내용은경지외모지상주의문서를 참고하십시오관련 문서무협소설용어무공목록무협 관련 용어클리셰 펼치기  접기 무공무공목록내공심법기타틀무공의 경지점혈검기점혈혈도논검문파틀무림의 세력정파구파일방무림맹사파사도련마교천마신교황실동창금군무림세가신비세력암중세력기물분류기보약독약영약기보기타 기보상태깨달음내상동귀어진심마절맥증주화입마칠공분혈환골탈태회광반조칭호경지선인승려협객검귀검마검성검선검신검왕검존검후검황도제만병지왕매화검수장문인사부사형제 명칭신투영물점소이천마웹소설천하제일인혈마후기지수흑의인기타무틀딱천살성분류무협 용어무협물용어관련 틀무협 용어분류웹소설 장르웹소설 매체웹소설 용어헌터물 용어 한국의 장르 판타지무공의 경지경지삼류이류일류절정초절정화경현경생사경검도검기검사검강신검합일검환이기어검술무형검심검관련 문서무협 용어틀분류무림의 세력무공 개요 종류 일반 확장 무공의 성취 검법 창작물의 경지 참고사항개요편집무협장르에서 무림인의 실력이나 성취를 표현하는 개념 중국어로는 경계라고 한다정통 무협으로부터삼류이류일류절정의 경지가 사용되었으며 여기에초절정이나화경현경생사경등이 추가되곤 한다 요즘은 현경까지는 자주 나오는 추세 더 나아가 무공의 성취에 따라서한중월야세계관처럼자연경공허경여의경과 같은 경지가 추가되기도 한다이러한 경지의 분류는 하나로 획일화되어 있는 기준이 아니기에 작가의 취향에 따라 전혀 다른 경지 및 체계를 따르거나 아예 무공의 경지라는 개념이 존재하지 않는 소설 역시 존재하며 경지의 차라는 것이 절대적이지도 않아서 상성이나 컨디션 전략에 따라 낮은 경지의 무인이 높은 경지의 무인을 무찌르는 경우도 있다현재는 무협뿐 아니라이능력이 나오는 모든 종류의 한국 장르소설에서 배경 세계를 따지지 않고 등장하곤 한다 대표적인 것이소드마스터무협 소설에서의 용어긴 하지만 실제로도 존재하는 용어로 뜻 역시 대동소이하다종류편집일반편집정통 무협에서 등장하는 일반적인 경지이다삼류 중소문파의 내문제자거나 대문파의 외문제자들이 대부분 이 경지에 도달해 있다이류 대문파 내문 제자 수준 초식과 내공을 동시에 활용하며 무공에 숙련되기 시작하는 단계일류 이 정도의 경지에 도달한 무인들은 대문파의 장로당주급 중소문파 장문인을 맡는다절정 대문파의 장문인이거나 원로급의 인물들이 이 경지에 도달해 있다 구무협에서는 최고의 경지이다확장편집로우 파워세계관에서는 절정초절정만으로 세계관 내에 적수가 없는 경우가 많지만 일반적인 구분법에서 좀 더 경지를 확장한 세계관의 경우 아래의 경지나 유사한 다른 경지들을 도입하기도 한다이 단계의 경지는 오로지 한국 무협물의 창작이다 구무협에는 이러한 경지가 존재하지 않았고 고수의 상징인 삼화취정 오기조원 등봉조극 등의 경지도 원래는 절정 고수 안에서의 단계적 구분을 위한 용어였으나 근래에는 더 높은 경지에서 사용되는 경우가 많다대표적으로 절정초절정경이 사용된다 물론 당연히 작품마다 각기 다르게 사용되며 작가가 창작한 다양한 경지를 사용하는 작품도 많이 있다 경지마다 어느 정도의 특징은 있으나 서로 다른 작품이면 같은 용어를 사용하더라도 같은 수준으로 묘사되지는 않는다 오로지 작가의 창작의 영역이므로 이 특성은 반드시 이 경지에서 사용되어야 한다와 같은 담론은 의미가 없다또한 같은 절정 혹은 그 이상 경지에 도달한 고수끼리라도 깨달음이나 숙련도에 따른 격차가 발생하는 것을 묘사하기 위해 하나의 경지에 초입중기후기극이라는 세세한 단계를 두기도 한다초절정 절정 이후의 경지 검기나 강기 등에 통달한 것으로 묘사된다 작가에 따라 초절정이 최고의 경지로 설정된 소설들도 적지 않다 작품에 따라 이 단계부터 환골탈태나 반로환동이 동반된다화경 화경 조화경 삼경의 첫 번째 단계로 작품에 따라 이 단계부터 삼화취정 오기조원 등봉조극 등의 구분을 사용하기도 한다 작품에 따라 검기를 넘어 어검술 등으로 구분을 주는 경우가 있다 삼경부터는로우 파워에서 확연히 벗어난하이 파워세계관일 가능성이 높다현경 현경 입신경 작품에 따라 어검술을 넘어 심검에 이르는 경지이다생사경 생사경 신화경 여기서부터는 보통 무협지에서 일반적인 사례로 등장하지는 않고 전설 속 신선의 경지로 취급하는 경우가 많다 하이 파워 세계관이라도 주인공이나 최종보스가 간신히 도달하는 영역이다무공의 성취편집노화순청등봉조극만류귀종반로환동반박귀진반선지경삼화취정오기조원우화등선천화난추출신입화환골탈태무극금강불괴만독불침도검불침한서불침의기상인심즉살검법편집검기상인검사검기성강검강압환심검신검합일이기어검술이기어검강창작물의 경지편집한중월야 세계관경지 역시 묵향에 영향을 받은 현대 무협의 특징을 보이나 생사경 다음으로 자연경 공허경 여의경 등 더 높은 경지가 존재한다묵향경지 화경 현경 생사경 등의 용어가 묵향으로 인해 유행하기 시작하였다전생검신경지회귀수선전의수선의 경지와무공의 경지중생지마교교주경지신드로이아 연대기영능경지언어의 주인이란설정수준참고사항편집사실 본 문서의 적혀 있는 경지의 내용은 가장 보편적으로 쓰이는 개념을 예시로써 적었을 뿐이다 당장 검환보다 신검합일이 높거나 절정이 화경보다 높은 경지인 소설도 있는 등 각각의 소설 또는 창작물마다 세계관과 설정이 다르다 본 문서의 예시는 장르소설 초창기에 높은 인기로 널리 알려지게 되어 저작권 개념이 희박했던 상황에서 많은 이들이 따라 썼고 여전히 쓰는 묵향의 설정을 대부분 참고하였다 따라서 이 문서에 등장하는 설정을 무협지라면 반드시 따라야 하는 것은 아니다이 문서의 내용 중 전체 또는 일부는무협소설용어문서의  판에서 가져왔습니다이전 역사 보러 가기 군산시시내버스 노선 펼치기  접기 미성동옥구읍대야면회현면성산면임피면서천군시내선심야 전용노선문서가 없는 노선은군산시 시내버스목록참고우성여객차량 노선 정보 개요 역사 특징 시간표 연계 철도역노선 정보편집군산시 시내버스 번기점전북특별자치도 군산시 성산면 성덕리금강호휴게소종점전북특별자치도 군산시 개사동개사동종점행첫차기점행첫차막차막차배차간격분노선금강호휴게소  채만식문화관  군산역  호덕교차로  구암현대아파트 야구장 미장삼거리  경문교  시외버스터미널 구시장신세계약국  해동가축병원  경암사거리  구시장입구   진포해양테마공원  근대역사박물관  희망루아파트  명산사거리 군산상일고등학교은파호수공원군산대정문 군산대교차로  개사경로당  개사동개요편집금강호휴게소과 개사동을 이어주는 노선이다역사편집년 월 일에 군산역이 현재 자리에 개업하면서군산 버스 번대와 같이 종점이 구암현대아파트에서 군산역으로 연장되었다예전에는 번이었으며 군산역 첫차가 시 개사동 첫차가 시 분 군산역 막차가 시 개사동 막차가 시 분이었으며 분 간격으로 운행했다이후 번으로 변경되었으며 분 간격으로 늘어났다 또한 군산역  호덕교차로  구암현대아파트  조촌삼성아파트 구간이 군산역  충량  개정파출소  월명체육관  조촌삼성아파트로 바뀌었다가 다시 철새조망대  군산역  호덕교차로  구암현대아파트  야구장  사정삼거리로 바뀌었다 이는 번도 마찬가지년 월 일 기점이군산역에서 금강미래체험관으로 연장되었다년 월 일 기점이 금강미래체험관 에서 금강호휴게소로 변경되었다특징편집 번을 제외한 번대 버스들은 전부 금강미래체험관  옥구파출소 구간을 공유한다번은대학로를 전 구간 경유하며 번과 번은 근대역사박물관과 월명터널로 돌아서 간다금강미래체험관 기점에서 탑승시 매표소 근처 구석에서 서 있으면 기사가 못보고 지나칠수 있으므로 철새조망대 주차장에 있는 화장실 입구 앞에서 서서 손을 흔들어 승차의사 표시를 하는걸 권장한다 해당 승차구역에는 버스정류장 표지판이 설치 되어 있지 않았다시간표편집아래는 번 시절 시간표다연계 철도역편집일반 철도역군산역새마을호 무궁화호 서해금빛열차이 문서의 내용 중 전체 또는 일부는군산 버스 번대문서의판에서 가져왔습니다이전 역사 보러 가기 하우스  개발  유통 플랫폼 장르액션 어드벤처호러출시년월 일한국어 지원자막 지원심의 등급전체 이용가세 이용가세 이용가청소년 이용불가평가용등급 분류 거부심의 예정한국심의 없음한국   등급 분류 거부심사 예정전연령금  관련 사이트상점 페이지 개요 시스템 요구 사항 스토리 등장인물 태비 멜로디 이웃 마티 고양이 인형 아빠 인형사 사회자 헨리 헨리의 보호자 헨리의 친구 후드티를 쓴 정체불명의 인물 키미코의 저주 키미코 키미코의 아빠 키미코의 엄마 키미코의 언니 엔딩 데드 엔딩 데드신 목록 노말 엔딩 몰살 엔딩 구원 엔딩 머드 월드 엔딩 광대 엔딩 더 이터널 쇼 엔딩 진 엔딩 시크릿 엔딩 평가개요편집티저 트레일러  에서 개발한의 정식 후속작이다시스템 요구 사항편집구분최소 사양권장 사양운영체제          프로세서           메모리    그래픽 카드                        버전  버전 저장 공간  사용 가능 공간  사용 가능 공간스토리편집끔찍한 폭풍이 몰아치는 가운데 태비는 또다시 끝없는 악몽에 갇히게 됩니다 년 공포 게임 하우스의 속편에서 저주의 비밀을 밝혀내거나 아니면 저주에 굴복하게 될 운명을 맞이하세요등장인물편집이 문서에스포일러가 포함되어 있습니다이 문서가 설명하는 작품이나 인물 등에 대한 줄거리 결말 반전 요소 등을 직간접적으로 포함하고 있습니다태비편집편에 이어서 이번 작품에서도 주인공이다 전작의 진엔딩에서 왼쪽 팔을 잃어 외팔이다멜로디편집이웃편집태비와 멜로디가 가족을 잃고 그들을 거두었으나 흑막에 의해 재앙을 당하게 된다마티편집태비하고 전작에서 같이 활동했던 달팽이다고양이편집전작에서 죽이거나 살릴 수 있는 고양이었는데 살린 것이 정사가 되었다인형편집전작에서 태비에게 목이 잘렸으나 후속작에서 살아있음이 드러난다 후속작에서는 입까지 움직이는 것도 모자라 신체의 일부가 움직인다아빠편집인형사편집사회자편집헨리편집헨리의 보호자편집번역이 없었을 때는 부모로 착각하기 좋다헨리의 친구편집후드티를 쓴 정체불명의 인물편집태비에게 키미코의 저주라는 게임을 주는 인물이다키미코의 저주편집작중 게임에서 나오는극중극이다 키미코라는 소녀를 조종하여 집에 내려진 저주와 싸우는 미니게임이다 작중 후드티를 입은 누군가가 게임을 준다 진 엔딩 클리어 후에키미코편집이 게임의 주인공인 소녀로 일본인 아니면 일본계로 추측된다키미코의 아빠편집키미코의 엄마편집키미코의 언니편집정식판에서는 동생으로 오역되었다엔딩편집데드 엔딩편집말만 엔딩이지 사실상 데드신으로서 도트 그래픽이었던 전작과 달리 손그림으로 바뀌었다 그야말로 작정하고료나로 가려는 제작자의 의도가 보인다데드신 목록편집노말 엔딩편집전작과 동일하게 덫과 총을 이용해 아빠를 죽이면 된다이번에는 총알이 발 들어있다클리어시 태비가 살아있는 인물들과 함께 를 본다 에서는 태비가 무대에 서서 인사를 하는 장면이 나온다몰살 엔딩편집구원 엔딩의 조건이였던 인물을 모두 죽이면 된다모든 조건을 만족하면 사악한 상태의 아빠가 나타나지만 눈물을 흘리며 딸을 안아주고 태비는 아빠에게 칼을 꽂는다이후 태비가 혼자 남아 를 본다 에서는 태비의 살인을 주제로 한 쇼가 나온다구원 엔딩편집집 안의 모든 사람과 동물을 살리면 볼 수 있는 엔딩 이웃 멜로디 고양이 쥐 개 말을 모두 살리면 된다모든 조건을 만족하면 아빠에게서 귀신이 사라져 착한 눈이 되어 태비를 껴안고 칭찬해주며 이후 모든 가족들과 동물들이 함께 앉아 를 보며 끝난다 에서는 노말 엔딩과 동일하게 태비가 무대에 서서 인사를 하지만 이번에는 머리 뒤에 후광이 있다머드 월드 엔딩편집광대 엔딩편집저녁 시에서 시 사이에 에서 광대가 나오며 가까이 가면 태비를 끌고 들어간다 이후 스테이지에서 광대를 잡으면 된다페이즈에서는 태비를 계속 따라가다가 구석으로 도망가 풍선을 불고 시간이 지나면 풍선이 터져 미끄러지는 물웅덩이를 생성한다 페이즈에서는 목만 남은 광대가 주기적으로 회전하는 공격을 날린다 패턴이 매우 단순한 편이라 시간만 좀 걸릴 뿐이지 한번 요령만 잡으면 클리어 자체는 어렵지 않다클리어시 새장 안에 있던 아이가 풀려나며 이후 태비가 서커스 천막이 불타는 내용의 를 보며 끝난다더 이터널 쇼 엔딩편집진 엔딩편집잠에서 깬 태비는 이상한 장소에 도착하고 거기서 자기처럼 반복되는 악몽을 꾸는 아이들을 만난다이후 태비는 그동안 자신이아이들이 루프되는 악몽을 꾸고 있다고 믿게 만든 다음 그걸 에 내보내는어느 리얼리티 쇼에 납치당해 있었다는 사실을 알게 된다 태비가 등장하는 쇼는 수백만 명이 보는 인기 프로그램이였다 쇼 이름은 태비의 저주받은 삶 대부분의 등장인물이 배우 또는 납치된 인물이였으며 심지어 태비의 아빠도 분장한 배우였다다만 묘사상 시간 루프는 진짜로 일어났던 것으로 보인다한 아이의 도움으로 결국 진행자는 죽고 카메라는 파괴되며 태비는 플레이어에게 감사의 말을 남기고 탈출한다 하지만 쇼는 끝나지 않았고 다른 진행자가 새로운 아이를 데려올 것이라 약속하며 한 소년이 태비가 나오는 쇼를 모티브로 한 게임을 플레이하며 끝난다시크릿 엔딩편집평가편집기준일메타스코어  유저 평점  상세 내용기준일종합 평가최근 평가매우 긍정적 평가 개 평가 개버프나 덫을 사용하지 않고 오직 칼과 총으로만 죽일 경우 업적이 해금된다여기서 달팽이 인형 거미 피자 배달원까지 다 죽이면 업적이 해금된다이때문에 가 태비의 아빠가 죽는 내용으로 끝났는데도 편에서 또 아빠가 등장한 것이다이 장면은 태비가 키미코의 저주를 플레이하던 모습과 동일하며 게임 이름도 비슷하다 즉 키미코 역시 이전의 희생자였으며 계속 새로운 희생자가 나오고 반복될 것이라는 암시로도 볼 수 있다 로도스도 전기에 등장하는 회색의 마녀에 대한 내용은칼라포세리아문서를 참고하십시오장갑기병 보톰즈 회색의 마녀 미정      장르리얼로봇감독오시이 마모루각본오시이 마모루야마무라 케이 캐릭터 디자인 원안키세 카즈치카캐릭터 디자인니시오 테츠야코지마 타카시오기소 신고오리지널메카니컬 디자인오오카와라 쿠니오메카니컬 디자인츠네키 시노부소노 유다이이시구치 쥬 이나다 와타루 의상 디자인 협력테라다 카츠야원작감수타카하시 료스케제작진 더보기 콘티미술 디자인타카하타 사토시 스에타케 야스미츠카네히라 카즈시게미술 감독혼조 유시색채 설계아베 나기사촬영 감독카와시타 유키 디렉터타자키 요타요코시마 토시히사나카지마 타케시 편집히다 아야 음향 감독와카바야시 카즈히로음악카와이 켄지기획선라이즈제작회색의 마녀 제작위원회프로듀서애니메이션 프로듀서출연사와시로 미유키안도 마부키등제작사선라이즈제작 협력 수입사미정배급사미정미정개봉일년 월 일제작미정 제작미정러닝타임분상영 등급미정관련 사이트 개요 공개 정보  키 비주얼 줄거리 등장인물 설정 등장 메카 주제가 제작 평가 개봉 전 개봉 후 제작 흥행 대한민국 일본 기타개요편집광기가 지배하는 끝 없는 전장부장갑기병 보톰즈시리즈 중 전 부작으로 구성된 완전 신작극장판애니메이션 감독은오시이 마모루 개봉일은 년 월 일제작 미정제작선라이즈의 주년 기념 작품이다공개 정보편집년 월 일선라이즈주년 기념 작품으로서 장갑기병 보톰즈 완전 신작 애니메이션이 발표되었다오시이 마모루감독은 밀리터리와 전쟁 영화를 좋아해 늘 전쟁 애니메이션을 하고 싶었는데스폰서쪽에서 자꾸경찰 애니메이션만 시켜서 년 동안 전쟁물은 못 만들었다고 한다이번에 기회가 와서 이 작품은 진짜 제대로 전쟁 영화로 만들었으며의욕도 크다고 한다기동경찰 패트레이버 공개 기념 이벤트에서텐진 히데타카는 오시이를 만났는데 보톰즈를 하면서 나는 로봇 애니메이션을 드디어 처음 만든다라고 했다고 한다 그래서 텐진 히데타카가 아니 그러면기동경찰 패트레이버는 뭔데요라고 했더니 오시이는 그건일상물이다라고 했다고 한다이 이야기를 들은이즈부치 유타카이토 카즈노리는 오시이다운 반응이네요 그리고 패트레이버는 일상물 맞아요라면서웃어 넘겼다오시이 감독은 보톰즈는 첫 작품이 방영됐을 당시부터 정말 좋아하는 작품이고 팬입니다 진심을 담아서 만들고 있습니다 너 또소바를 먹는 장면 넣을 거냐고말하시는 분들도 있지만 진지하게 하고 있습니다 진지하게 전쟁 액션을 만들고 있습니다라고 코멘트했다편집초탄 영상특보년 만에긴가 반조가 다시 한 번나레이션을 맡았다본 예고본 예고 초 키 비주얼편집제작 결정 비주얼제작 티저 비주얼줄거리편집아스트라기우스 은하계를 양분하는길가메스와발라란트 이 두 세력은 원인조차 확실하지 않은 전쟁을 년 가까이 이어오고 있었다백년 전쟁 말기 아스가르드 항성계 제행성 발큐리아 의 전선 기지에 한 명의 여성 장교 마키 슈타우펜베르크가 부임한다 그녀는 잡다한 병사들로 구성된형벌부대속에서 아무리 가혹한 작전이라도 단 한 명만 살아남는다는 이유로 마녀라고 불리는 병사 애쉬 밤프스를 조사하는 임무를 비밀리에 맡고 있었다전장의 진실은 전장에서만 알 수 있다애쉬의 부대에 명령된 적진 강행 강하 작전에 마키는 아머드 트루퍼 파일럿으로서 참가를 결심한다생존이 불가능해 보이는 작전 속에서 전황은 시시각각 절망으로 치닫는다 전화 속에서 애쉬를 쫓는 마키는 이윽고 그녀에게 숨겨진 진실에 다가서게 되는데등장인물편집애쉬 밤프스 성우사와시로 미유키목숨은 소모품으로 바뀌었다하지만반드시 되살아나는마녀가 있다제 강하엽병대대의 상사형벌부대인 제중대에 소속된  파일럿 어떤 혹독한 작전이라도 생존자로 귀환해 마녀라 불리며 두려움을 받고 있다그녀의 부대는 소대장이 없어서 밤프스 소대라고 불리며 문제 병사들로 구성되어 있다본작의 주연인물이능생존체를 암시하듯 끝없는 전쟁으로 병사가 병기의 소모품으로 전락한본말전도의 시대에서 살아남는 존재로 소개되며 이 때문에 마녀라고 불린다 마침 그녀의 이름인 애쉬는 영어로재라는 뜻이기에 본작의 제목과 상통한다키리코 큐비와 달리 죽지 않는다가 아니라 되살아난다고 소개되는데 이게역경속의역전에 빗댄 것인지 아니면이능자나퍼펙트 솔저의 능력을 말하는지는 알 수 없다페일젠 파일즈시절 나온 설정인근사치일 가능성도 있다마키 슈타우펜베르크 성우안도 마부키제 독립선전중대의 대위상급 사령부에서 전장 취재를 위해 부하와 함께 발키리아  전선 기지에 파견된다하지만 진짜 목적은 죽지 않는 병사인 애쉬 밤프스를 조사하는 것이었다전장에서의 진실을 추적하기 위해 그녀도  파일럿으로서 밤프스 소대의 위험한 강행 강하 작전에 동행한다애쉬 밤프스에 대해 조사하기 위해 파견된 장교로치나를 연상시키는 설명문과 차 은하대전 말기라는 시기 때문에 이능생존체 후보자들을 뒤지고 다니던요란 페일젠이나 페독 워컴의 관계자라는 설이 있다알릭스 발라크 성우미키 신이치로제 독립선전중대 소속의 중사마키의 직속 부하로서 수많은 전장을 함께해 왔지만 이번에도 함께 작전에 동행한다이그니스 슈바인슈타이거 성우카지 유우키제 독립선전중대 소속의 하사원래는 다른 부대에 소속돼 있었지만 이번 임무부터 마키 부대에 배속되었다별명은 슈바이니프리츠 게르스돌프 성우나카무라 유이치밤프스 소대 소속 일병타 부대에서 수많은 문제를 일으켜 형벌부대에 입대했다 성격은 고집스럽고 거칠지만  조종에 뛰어난 자질이 있다브룬하르트 뮐러 성우츠루오카 사토시밤프스 소대 소속 일병형벌부대에 자원함으로써 부과되던 징역이 면제되었다 흉악한 병사아드리안 다이슬러 성우스기타 토모카즈밤프스 소대 소속의 일병 조종 적성이 높고 다수의 군공상을 받은 병사였지만 과거의 항명 행위 때문에 징계 부대로 입대맷 훔멜스 성우미야케 켄타밤프스 소대 소속의 일병화력 지원형 의 파일럿 각지에서 용전하지만 어느 사건으로 인해 본인의 강한 희망에 따라 특례로 형벌부대에 입대했다솔티그 반 군나르 성우챠후린제 강하엽병대대 대령아스가르드 성계 제행성 발키리아 의 전선 기지 사령관비드 힐데그란트 성우오오츠카 호츄제 강하엽병대대 부속 헌병 대위기지에의 군규 유지조사의 지휘를 담당하고 있다메데우슈 유리안 포돌스키 성우오노 다이스케제 강하엽병대대 부속 헌병 소위힐데브란트의 부관으로 기지에 파견된 마키 일행을 감시하라는 명령을 받는다바이스바일러 성우스고 타카유키제 강하엽병대대 부속 특무 소위정비 중대 소속 정비병으로서 일류의 솜씨를 갖추고 기지 의 정비 관리를 전담하고 있다올리버 성우사쿠라이 타카히로제 강하엽병대대 부속 상급 상사정비 중대에 소속된 바이스바일러의 부관정비병 소녀 성우우에사카 스미레바이스바일러와 함께 정비 중대에서 일하는 소녀설정편집등장 메카편집스코프 독발키리아  전선 사양길가메스군의 주력 범용성이 극히 뛰어나며대량 생산되고 있다개조용 파츠도 많고 수많은 전장에서 현지 개량형이 파생 본 기체는 행성 발키리아 의 환경에 맞게 개량되었다 두부의 삼련 터렛 렌즈와 다리 부분의 글라이딩 휠을 이용한 고속 이동롤러 대시 팔을 신축시켜 타격을 주는 암 펀치 등 특징적인 메커니즘 외에도 헤비 머신건의 자동 장전 장치가 추가되어 있다사막색위장색으로 도장된 기체와 원조 스코프 독의 컬러를 채용한 녹색 기체가 등장 원작의 스코프 독에 비해 머리 크기가 작아지고등신대가 늘어났으며 다리의 롤러 대쉬가무한궤도로 변경되고 무장의 양상이 상당히 변경되었다 또한 회색의 마녀 버전 스코프 독에는포탑 형태로 변형하는 기믹이 추가되었는데 다리를 뒤로 굽혀 접고머신건을 잡은 오른팔의팔꿈치를 뒤로 꺾어 올려총구를 머리 위로 올린 채 사격한다 암 펀치 대신파일 벙커를 달고 있거나 증가장갑을 붙이고 공수투하 하는 장면도 나타난다 시절부터 이어지던 전통의디자인도 현용 전투기와 비슷한 느낌의 반투명 단색 로 달라졌다 몸통을 앞뒤로 굽힐 수 있게 축관절이 추가되었고 바이저를 올려도 탑승자의 얼굴이 노출되지 않는 디자인으로 바뀐 덕분에 시선을 치켜올리는 동작을 자연스럽게 할 수 있게 되었다라는 제식명이 밝혀졌는데 원래 기본형 스코프독의 와는 다르며 현지 개량형이라는 설정이 붙게 되었다지휘관기한쪽 어깨를 붉은 색으로 부분도색하고 소형 블레이드 안테나로 추정되는 물체를 단 형태라이징 비틀공식 홈페이지에 올라오지도 않았는데메가하우스에서 제품을 예약을 받으면서먼저 공개되었다이름과 렌즈부의 형태로 볼 때다이빙 비틀계열인 것으로 보인다 특이하게도 스코프 독의 콕핏을 앞에다 이어 붙인 복좌형으로 추정되는 기체도 있다블로커본 예고에서 첫 등장한  적색으로 도색되어 있다 처음에는 완전한 신기체로도 추정됐으나 비슷한 디자인의 블로커로 확정됐다원작 에선 화에만 등장했을 정도로 마이너한 기체이기 때문인지는 몰라도 스코프 독보다 훨씬 과감하고리얼로봇스럽게 리파인되었다주제가편집제작편집주제가원제목번역명번안명  노래작사작곡편곡주제가 애니메이션 정보 콘티연출작화감독평가편집개봉 전편집감독이오시이 마모루로 밝혀지면서 팬들 사이에서는 기대와 우려가 교차하고 있다 기대하는 쪽에서는 오시이 특유의 진지하고 어두운 분위기가 보톰즈의 세계관과 잘 어울린다는 점 그리고기동경찰 패트레이버 극장판등에서 보여준 뛰어난 연출력과 영상미를 근거로 높은 완성도를 기대하고 있다 특히 기존 보톰즈의리얼로봇물다운 밀리터리적 분위기와 오시이 특유의 사실적인 공간 연출이 결합할 경우 어떤 결과물이 나올지에 대한 기대를 받고 있다반면 우려의 목소리도 만만치 않다 오시이는 작품의 주제와 메시지를 강조하는 과정에서 서사 진행을 늦추거나장광설와 사색적인 장면을 길게 배치하는 경우가 많고 직접적인 설명 없이 장면의 구성과 대사 연출 등을 통해 관객이 의미를 해석하도록 만드는 경우도 많다 이러한 작풍은 관객에 따라 깊이 있는 연출로 받아들여지기도 하지만 지나치게 장황하고 지루하다는 평가 역시 많기에 호불호가 크게 갈린다 긴 대사와 정적인 장면 느린 전개가 작품의 분위기와 주제의식을 강화하는 경우도 있지만 반

In [8]:
df['content']

0     라이베리아 공화국 대통령 펼치기  접기 초대제대제대제대조셉 젠킨스 로버츠스티븐 앨런...
1     경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오보드게임 벚꽃 내리는...
2     군산시시내버스 노선 펼치기  접기 미성동옥구읍대야면회현면성산면임피면서천군시내선심야 ...
3     하우스  개발  유통 플랫폼 장르액션 어드벤처호러출시년월 일한국어 지원자막 지원심의...
4     로도스도 전기에 등장하는 회색의 마녀에 대한 내용은칼라포세리아문서를 참고하십시오장갑...
5     카드 앙 시엘 카드 목록코스트코스트드로디버그리부트무브메모리 리크변신브레이크 포인트서...
6
7      개요 시스템 종류 여담개요편집워크래프트 의 종족 공통 건물 중 하나영어를 그대로 ...
8     크레인들 펼치기  접기 노스 웨스턴 철도 소속크랭키칼리빅 미키레지테스협궤 철도 소속...
9     제임스 로니 관련 틀 펼치기  접기 로스앤젤레스 다저스역대 라운드 지명선수 펼치기 ...
10    한시적 넘겨주기로 연결되는 다른 문서에 대한 내용은 아래 문서를 참고하십시오월 일 ...
11    에서의 탱킹에 대한 내용은탱커문서를 참고하십시오 개요 의도 및 방식 탱킹을 하는 이...
12     개요 실존 인물 가상 인물개요편집년 기준 는 명이 사용중인일본의 성씨다한국에도 해...
13
14
15    극장판 펼치기  접기 기기기기기시한장치의 마천루줄거리쿠키 영상번째 표적줄거리쿠키 영...
16     개요 시스템 종류 여담개요편집워크래프트 의 종족 공통 건물 중 하나영어를 그대로 ...
17    상위 문서영천시관련 문서영천시청도군경상북도정치 펼치기  접기 경산시경주시구미시김천시...
18     펼치기  접기 무인 시리즈애니메이션이나즈마 일레븐이나즈마 일레븐 이나즈마 일레븐 ...
19
20    년 이라크 봉기  반군에 의해 파괴된 이라크 보안군의 전차기간년월 일월 일장소이라크...
21     쇼트트랙 스피드 스케이팅  시즌 펼치기  접기  쇼트트랙 월드컵 차 쇼트트랙 월드...
22    상위 문서불꽃 파이터즈역대 전적 시즌 개요 시즌 포맷 변경점 엔트리    연천 미라...
23    편집 보호된 문서입니다 문서의 탭을 확인하세요항성의진화 펼치기  접기 초기태양 질량...
24
25    상위 문서김환희골 때리는 그녀들 개요 클럽 액셔니스타개요편집김환희의골 때리는 그녀들...
26
27
28    구마모토현시정촌 펼치기  접기 정령지정도시현청정령구마모토시 하위 행정구역시아소시아마...
29
30    손자인물은는 여기로 연결됩니다 제나라의 손자에 대한 내용은손빈문서를 참고하십시오사기...
31     개요 배경 및 개발 출시 및 생산 폴로네즈 폴로네즈 카로 폴로네즈 카로 플러스 파...
32     쇼트트랙 스피드 스케이팅  시즌 펼치기  접기  쇼트트랙 월드컵 차 쇼트트랙 월드...
33    사한국정보평가협회가 운영하는 국가공인민간자격증에 대한 내용은 정비사문서를 참고하십시...
34    상위 문서불꽃 파이터즈역대 전적 시즌 개요 시즌 포맷 변경점 엔트리    연천 미라...
35
36    상위 문서김환희골 때리는 그녀들클럽 경력김환희시즌 소속 팀 액셔니스타소속 기간년월 ...
37     시즌에 대한 내용은안양 정관장 레드부스터스 시즌문서를 참고하십시오한국프로농구참가 ...
38    다른 지 제네레이션 시리즈에서의 잔스파인에 대한 내용은잔스파인문서를 원작의 파라 그...
39
40     시즌에 대한 내용은부산 저축은행 읏맨 시즌문서를 참고하십시오리그 남자부참가 구단 ...
41
42
43    상위 문서토오사카 린작중 행적이 문서에스포일러가 포함되어 있습니다이 문서가 설명하는...
44    상위 문서김주성야구선수 개요 아마추어 시절 트윈스  시즌  시즌  시즌  시즌  시...
45    상위 문서리그 오브 레전드증강리그 오브 레전드의증강실버골드프리즘 개요 공용 증강 거...
46    라이베리아 공화국 대통령 펼치기  접기 초대제대제대제대조셉 젠킨스 로버츠스티븐 앨런...
47
48    프린세스 메이커 의 인물에 대한 내용은아스파르프린세스 메이커 문서를 참고하십시오 개...
49    상위 문서년연도별 사건 문서 바로가기년 사건년 사건년 사건 개요 실제 월 월 월 월...
Name: content, dtype: str