In [6]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [7]:
import random
df['요일'] = 0

for i in range(8):
    df.iloc[i,9] = random.randint(0,6)

In [3]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python   5
2번    강태원   구로고  184   40   35   50  55  25        Java   4
3번    강호림   구로고  168   80   75   70  80  75  Javascript   3
4번    김수찬   구로고  187   40   60   70  75  80         NaN   4
5번    김재욱   구로고  188   15   20   10  35  10         NaN   3
6번    박동현  디지털고  202   80  100   95  85  80           C   4
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   4
8번    승근열  디지털고  190  100   85   90  95  95          C#   3

In [8]:
# 0-일요일,1-월요일,2-화요일,3-수요일,4-목요일,5-금요일,6-토요일
# 출력하시오.
# (함수 적용)
def cal_change(x):
    if x == 0: return '일요일'
    elif x == 1: return '월요일'
    elif x ==2: return '화요일'
    elif x ==3: return '수요일'
    elif x ==4: return '목요일'
    elif x ==5: return '금요일'
    else: return '토요일'

df['요일'] = df['요일'].apply(cal_change)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  목요일
2번    강태원   구로고  184   40   35   50  55  25        Java  일요일
3번    강호림   구로고  168   80   75   70  80  75  Javascript  목요일
4번    김수찬   구로고  187   40   60   70  75  80         NaN  수요일
5번    김재욱   구로고  188   15   20   10  35  10         NaN  월요일
6번    박동현  디지털고  202   80  100   95  85  80           C  수요일
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  목요일
8번    승근열  디지털고  190  100   85   90  95  95          C#  토요일

In [12]:
data = {
    '번호':['1번','2번','3번','4번','5번','6번','7번','8번'],
    '이름':['홍길동','유관순','이순신','강감찬','김구','김유신','홍길자','홍길순'],
    '달러':['$19,700','$18,400','$16,800','$18,700','$18,800','$20,200','$18,800','$19,000'],
    '우대':[90,40,80,40,15,80,55,100]
}

df = pd.DataFrame(data)
df.set_index('번호',inplace=True)

In [13]:
df['금액'] = 0 # 컬럼추가

# 금액컬럼을 추가 하시오. ( 금액 : 달러 + 달러 x 우대 x 0.01 )
# 우대 50이상인 사람에게 달러+달러X우대x0.01
# 우대 50미만 달러

# 달러 -> int변경($,쉼표) 표시 제거
# str.replace
df['달러'] = df['달러'].str.replace('$','')
df['달러'] = df['달러'].str.replace(',','').str.strip().astype(int)
df

     이름     달러   우대  금액
번호
1번  홍길동  19700   90   0
2번  유관순  18400   40   0
3번  이순신  16800   80   0
4번  강감찬  18700   40   0
5번   김구  18800   15   0
6번  김유신  20200   80   0
7번  홍길자  18800   55   0
8번  홍길순  19000  100   0

In [14]:
# 2개가 넘어와야 함. df['달러'],df['우대']
def cal_change(df2):
    if df2['우대']>=50:
        return df2['달러'] + (df2['달러'] * df2['우대'] * 0.01)
    else:
        return df2['달러']    

df['금액'] = df.apply(cal_change,axis=1)
df

     이름     달러   우대       금액
번호
1번  홍길동  19700   90  37430.0
2번  유관순  18400   40  18400.0
3번  이순신  16800   80  30240.0
4번  강감찬  18700   40  18700.0
5번   김구  18800   15  18800.0
6번  김유신  20200   80  36360.0
7번  홍길자  18800   55  29140.0
8번  홍길순  19000  100  38000.0

In [60]:
df.columns

Index(['행정구역', '2026년08월_총인구수', '2026년08월_세대수', '2026년08월_세대당 인구',
       '2026년08월_남자 인구수', '2026년08월_여자 인구수', '2026년08월_남여 비율'],
      dtype='str')

In [68]:
df = pd.read_csv('file/jumin08_2.csv')
# 1,2,3,4,5번까지 인구수 합계를 구하시오.
df2 = df[['행정구역', '2026년08월_총인구수']]
df3 = df2[1:6]
df3['2026년08월_총인구수'] = df3['2026년08월_총인구수'].str.replace(',','').astype(int)
df3.info()
df3.describe()
df3['2026년08월_총인구수'].sum()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 1 to 5
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   행정구역           5 non-null      str
 1   2026년08월_총인구수  5 non-null      int64
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

np.int64(21079357)