In [ ]:
# 1. item_name 당 주문서 개수를 출력하시오. 10개만 출력
# 2. item_name 당 주문 총량(quantity)을 출력하시오.
# 3. 가장 많이 주문한 item_name  10개를 출력하시오.

# 4. 주문당 평균 금액을 출력하시오.
# 5. 한 주문에 10달러 이상 사용한 주문 번호(id) 출력하시오.
# Chicken Bowl을 2개 이상 구매한 주문서 출력하시오.

In [36]:
import pandas as pd
df = pd.read_csv('file/chipotle.tsv', sep = '\t')

In [ ]:
# ============================================================
# 1. item_name 당 주문서 개수 출력 - 10개만
# groupby : 같은 값끼리 묶기
# count : 개수 세기
# head(10) : 앞에서 10개
# ============================================================

# df.groupby('item_name')['order_id'].count().head(10)


# ============================================================
# 2. item_name 당 주문 총량(quantity)
# quantity : 수량
# sum : 합계
# ============================================================

# df.groupby('item_name')['quantity'].sum().sort_values(ascending=False)


# ============================================================
# 3. 가장 많이 주문한 item_name 10개
# sort_values : 값 정렬
# ascending=False : 큰 값부터 정렬
# ============================================================

# df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(10)


# ============================================================
# 4. 주문당 평균 금액
# replace : $ 제거
# astype(float) : 숫자(실수)로 변경
# mean : 평균
# ============================================================

df['item_price'] = df['item_price'].str.replace('$', '')
df['item_price'] = df['item_price'].astype(float)
# df.groupby('order_id')['item_price'].sum()
order_price = df.groupby('order_id')['item_price'].sum()

# order_price.mean()


# ============================================================
# 5. 한 주문에 10달러 이상 사용한 주문번호(id)
# >= 10 : 10 이상인 데이터 찾기
# index : 주문번호(order_id) 가져오기
# ============================================================

order_price[order_price >= 10].index


# ============================================================
# 6. Chicken Bowl을 2개 이상 구매한 주문서
# & : 두 조건을 모두 만족
# ============================================================

# df[(df['item_name'] == 'Chicken Bowl') & (df['quantity'] >= 2)]

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834],
      dtype='int64', name='order_id', length=1834)

In [ ]:
# Chicken Bowl을 2개 이상 구매한 주문서 출력하시오.
filt = (df['item_name']== 'Chicken Bowl') & (df['quantity']>=2)
df[filt]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
154,70,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
282,124,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",17.50
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
415,181,2,Chicken Bowl,[Tomatillo Red Chili Salsa],17.50
654,271,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
976,401,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1017,418,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Black Beans]]",17.50
1106,457,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1429,578,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...",22.50
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",26.25
1588,643,2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",17.50
1832,741,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Sour Cream,...",21.96
2075,837,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
2106,848,2,Chicken Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",17.50
2339,932,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",16.98
2510,997,2,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",22.50
2525,1004,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",21.96
2580,1023,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
2771,1100,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
2942,1170,2,Chicken Bowl,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",21.96
3080,1227,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
3133,1249,2,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",16.98
3151,1257,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
3423,1374,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",17.50
3508,1410,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...",21.96
3612,1447,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",16.98
3618,1449,2,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
3663,1465,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
3843,1540,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Pinto...",21.96
3976,1593,2,Chicken Bowl,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",16.98
4423,1764,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",22.50
4435,1767,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",17.50

In [17]:
df.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

In [23]:
df.groupby('order_id')['item_price'].count()

order_id
1       4
2       1
3       2
4       2
5       2
       ..
1830    2
1831    3
1832    2
1833    2
1834    3
Name: item_price, Length: 1834, dtype: int64

In [21]:
filt = df.groupby('order_id')['item_price'].sum()>=10
df.groupby('order_id')['item_price'].sum()[filt]

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [60]:
df['item_name'].value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Chips                                    211
Steak Bowl                               211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       2
Crispy Tacos                               2
Salad                                      2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

In [59]:
# 2. item_name 당 주문 총량(quantity)을 출력하시오.
df.groupby('item_name')['quantity'].sum().sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [52]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [54]:
# item_name 당 주문서 개수를 출력하시오. 10개만 출력
df['item_name'].value_counts().head(10)

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Chips                           211
Steak Bowl                      211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

In [39]:
df.shape

(4622, 5)

In [40]:
df['order_id'].unique()

array([   1,    2,    3, ..., 1832, 1833, 1834], shape=(1834,))

In [41]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [48]:
df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float)

In [50]:
df['item_price'].sum()

np.float64(34500.16)

In [49]:
# df.info()
df['order_id'] = df['order_id'].astype(str)
df.describe()

          quantity   item_price
count  4622.000000  4622.000000
mean      1.075725     7.464336
std       0.410186     4.245557
min       1.000000     1.090000
25%       1.000000     3.390000
50%       1.000000     8.750000
75%       1.000000     9.250000
max      15.000000    44.250000

In [ ]:
df.columns
df.head()
df.describe() # item_price가 나타나지 않음

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [18]:
# 1. item_name 당 주문서 개수를 출력하시오. 10개만 출력
item_count = df['item_name'].value_counts()[:10]
item_count
# item_count.index[0]

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Chips                           211
Steak Bowl                      211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

In [36]:
df.groupby('item_name')['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

In [ ]:
# 2. item_name 당 주문 총량(quantity)을 출력하시오.
item_quantity = df.groupby('item_name')['quantity'].sum()
item_quantity[:10] # item당 주문 총량을 출력
item_quantity.sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [24]:
# 3. 가장 많이 주문한 item_name  10개를 출력하시오.
df['item_name'].value_counts()[:10]

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Chips                           211
Steak Bowl                      211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

In [ ]:
df['item_name'].unique()[:10]  # 주문상품 종류

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos']
Length: 10, dtype: str

In [4]:
df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float)
df['item_price'] = df['item_price'].apply(lambda x: float(x[1:]))
df.describe()

TypeError: 'float' object is not subscriptable

In [ ]:
# 주문당 평균 계산금액을 출력
df.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

In [ ]:
# 한 주문에 50달러 이상 사용한 index.
# chipo_orderid_group = df.groupby('order_id').sum()
# results = chipo_orderid_group[chipo_orderid_group.item_price >= 50]

# results.index.values
# results.count()
# df['item_price'] = df['item_price'].str.replace('$','').str.strip().astype(float)
# df['item_price'] = df['item_price'].apply(lambda x: float(x[1:]))
# df.groupby('order_id')['item_price'].sum()

AttributeError: Can only use .str accessor with string values, not floating